# Generated by Django 5.2 on 2025-09-02 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("generate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="public/%Y/%m/")),
                ("title", models.CharField(blank=True, max_length=140)),
                ("caption", models.CharField(blank=True, max_length=240)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_public_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_session_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="generate.generationjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "public_photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="gallery.publicphoto",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("job__isnull", False), ("user__isnull", False)
                        ),
                        fields=("user", "job"),
                        name="uniq_like_user_job",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("public_photo__isnull", False), ("user__isnull", False)
                        ),
                        fields=("user", "public_photo"),
                        name="uniq_like_user_public",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("guest_session_key__gt", ""), ("job__isnull", False)
                        ),
                        fields=("guest_session_key", "job"),
                        name="uniq_like_guest_job",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("guest_session_key__gt", ""),
                            ("public_photo__isnull", False),
                        ),
                        fields=("guest_session_key", "public_photo"),
                        name="uniq_like_guest_public",
                    ),
                ],
            },
        ),
    ]
