# Generated by Django 5.2 on 2025-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_add_comment_parent_and_nullable_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicphoto",
            name="view_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
