# Generated by Django 5.2 on 2025-09-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_publicphoto_view_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentlike",
            options={
                "verbose_name": "Лайк комментария",
                "verbose_name_plural": "Лайки комментариев",
            },
        ),
        migrations.RemoveConstraint(
            model_name="commentlike",
            name="uq_comment_user_like",
        ),
        migrations.AddField(
            model_name="commentlike",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="photolike",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("comment", "user"),
                name="uq_comment_user_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("comment", "session_key"),
                name="uq_comment_session_like",
            ),
        ),
        migrations.AddConstraint(
            model_name="photolike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__isnull", False)),
                fields=("session_key", "photo"),
                name="uix_photo_like_session_photo",
            ),
        ),
    ]
