# Generated by Django 5.2 on 2025-09-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_commentlike_options_and_more"),
        ("generate", "0005_merge_20250914_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicphoto",
            name="source_job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_entry",
                to="generate.generationjob",
            ),
        ),
    ]
