# Generated by Django 5.2 on 2025-09-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0008_publicphoto_source_job"),
        ("generate", "0005_merge_20250914_0944"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="like",
            options={
                "verbose_name": "Лайк задачи",
                "verbose_name_plural": "Лайки задач",
            },
        ),
        migrations.RemoveConstraint(
            model_name="commentlike",
            name="uq_comment_user_like",
        ),
        migrations.RemoveConstraint(
            model_name="commentlike",
            name="uq_comment_session_like",
        ),
        migrations.RemoveConstraint(
            model_name="like",
            name="uix_like_user_job",
        ),
        migrations.RemoveConstraint(
            model_name="photolike",
            name="uix_photo_like_user_photo",
        ),
        migrations.RemoveConstraint(
            model_name="photolike",
            name="uix_photo_like_session_photo",
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="photocomment",
            name="is_visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="photolike",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("comment", "user"),
                name="uq_comment_like_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="commentlike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key", ""), _negated=True),
                fields=("comment", "session_key"),
                name="uq_comment_like_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job__isnull", False), ("user__isnull", False)),
                fields=("user", "job"),
                name="uq_job_like_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="photolike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("photo", "user"),
                name="uq_photo_like_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="photolike",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key", ""), _negated=True),
                fields=("photo", "session_key"),
                name="uq_photo_like_session",
            ),
        ),
    ]
