# Generated by Django 5.2 on 2025-09-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_alter_like_options_and_more"),
        ("generate", "0005_merge_20250914_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicphoto",
            name="source_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="public_entries",
                to="generate.generationjob",
            ),
        ),
    ]
