# Generated by Django 5.2 on 2025-09-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0010_alter_publicphoto_source_job"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photocomment",
            options={
                "ordering": ("created_at", "pk"),
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="photocomment",
            name="likes_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="publicphoto",
            name="comments_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="publicphoto",
            name="likes_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
