# Generated by Django 5.2.6 on 2025-10-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_photocomment_options_photocomment_likes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_id', models.IntegerField(help_text='ID в JSON файле', unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('prompt', models.TextField(verbose_name='Промт')),
                ('image', models.ImageField(help_text='Загрузите изображение для примера', upload_to='slider_examples/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('alt', models.CharField(max_length=200, verbose_name='Alt текст для изображения')),
                ('steps', models.IntegerField(default=28, verbose_name='Количество шагов')),
                ('cfg', models.FloatField(default=7.0, verbose_name='CFG Scale')),
                ('ratio', models.CharField(choices=[('1:1', '1:1 (квадрат)'), ('3:2', '3:2 (фото)'), ('4:3', '4:3 (стандарт)'), ('16:9', '16:9 (широкий)'), ('9:16', '9:16 (вертикальный)')], default='3:2', max_length=10, verbose_name='Соотношение сторон')),
                ('seed', models.CharField(default='auto', help_text="Введите число или 'auto' для случайного", max_length=20, verbose_name='Seed')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Пример слайдера',
                'verbose_name_plural': 'Примеры слайдера',
                'ordering': ['order', 'json_id'],
            },
        ),
    ]
