# Generated by Django 5.2.6 on 2025-10-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_sliderexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicphoto',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'На модерации'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
