# Generated by Django 5.2.6 on 2025-10-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_add_moderation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicphoto',
            name='moderation_status',
        ),
        migrations.RemoveField(
            model_name='sliderexample',
            name='ratio',
        ),
    ]
