# Generated by Django 5.2.6 on 2025-10-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_remove_ratio_field_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderexample',
            name='json_id',
            field=models.IntegerField(blank=True, help_text='ID в JSON файле', null=True, unique=True),
        ),
    ]
