# Generated by Django 5.2.6 on 2025-10-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_make_json_id_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderexample',
            name='json_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID в JSON файле', null=True),
        ),
    ]
