# Generated by Django 5.2.6 on 2025-10-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_remove_unique_constraint_json_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderexample',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для примера', null=True, upload_to='slider_examples/', verbose_name='Изображение'),
        ),
    ]
