# Generated by Django 5.2.6 on 2025-10-12 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0017_make_image_optional"),
        ("generate", "0021_add_video_prompt_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("image_url", models.URLField(max_length=500)),
                ("is_video", models.BooleanField(db_index=True, default=False)),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("is_nsfw", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "generation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_entries",
                        to="generate.generationjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Изображения галереи",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="gallery_ima_user_id_42d8a9_idx",
                    ),
                    models.Index(
                        fields=["user", "is_video"],
                        name="gallery_ima_user_id_b88ef5_idx",
                    ),
                ],
            },
        ),
    ]
