# Generated by Django 5.2.6 on 2025-10-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0018_image"),
        ("generate", "0021_add_video_prompt_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(max_length=500, verbose_name="URL видео"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="public_videos/%Y/%m/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Название"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Описание"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Опубликовано"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Просмотры"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Лайки"
                    ),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Комментарии"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="gallery.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "source_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_video_entries",
                        to="generate.generationjob",
                        verbose_name="Задача генерации",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_public_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публичное видео",
                "verbose_name_plural": "Публичные видео",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_visible",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Видимый"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Лайки"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="gallery.videocomment",
                        verbose_name="Родительский комментарий",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="gallery.publicvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к видео",
                "verbose_name_plural": "Комментарии к видео",
                "ordering": ("created_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="VideoCommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="gallery.videocomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк комментария к видео",
                "verbose_name_plural": "Лайки комментариев к видео",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("comment", "user"),
                        name="uq_video_comment_like_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_key", ""), _negated=True),
                        fields=("comment", "session_key"),
                        name="uq_video_comment_like_session",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="gallery.publicvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лайк видео",
                "verbose_name_plural": "Лайки видео",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("video", "user"),
                        name="uq_video_like_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_key", ""), _negated=True),
                        fields=("video", "session_key"),
                        name="uq_video_like_session",
                    ),
                ],
            },
        ),
    ]
