# Generated by Django 5.2.6 on 2025-10-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0019_publicvideo_videocomment_videocommentlike_videolike"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Слаг"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Категория видео",
                "verbose_name_plural": "Категории видео",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AlterField(
            model_name="publicvideo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="gallery.videocategory",
                verbose_name="Категория",
            ),
        ),
    ]
