# Generated by Django 5.2.6 on 2025-10-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0023_jobsave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobsave",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="VideoSliderExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "json_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID в JSON файле",
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("prompt", models.TextField(verbose_name="Промт")),
                (
                    "video_url",
                    models.URLField(max_length=500, verbose_name="URL видео"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Опционально: изображение-постер для видео",
                        null=True,
                        upload_to="slider_video_examples/",
                        verbose_name="Постер (превью)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "steps",
                    models.IntegerField(default=28, verbose_name="Количество шагов"),
                ),
                ("cfg", models.FloatField(default=7.0, verbose_name="CFG Scale")),
                (
                    "seed",
                    models.CharField(
                        default="auto",
                        help_text="Введите число или 'auto' для случайного",
                        max_length=20,
                        verbose_name="Seed",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Видео-пример слайдера",
                "verbose_name_plural": "Видео-примеры слайдера",
                "ordering": ["order", "json_id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="gallery_vid_is_acti_7ae520_idx",
                    )
                ],
            },
        ),
    ]
