# Generated by Django 5.2.6 on 2025-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0024_alter_jobsave_id_videosliderexample"),
    ]

    operations = [
        migrations.AddField(
            model_name="videosliderexample",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="slider_video_examples/%Y/%m/",
                verbose_name="Видео файл",
            ),
        ),
        migrations.AlterField(
            model_name="videosliderexample",
            name="video_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL видео"
            ),
        ),
    ]
