# Generated by Django 5.2.7 on 2025-10-22 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0025_videosliderexample_video_file_and_more"),
        ("generate", "0026_videopromptsubcategory_videoprompt_subcategory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hides",
                        to="generate.generationjob",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_hides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Скрытие задачи",
                "verbose_name_plural": "Скрытия задач",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "job"), name="uq_job_hide_user"
                    )
                ],
            },
        ),
    ]
