# Generated by Django 5.2.6 on 2025-10-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_gate_enabled', models.BooleanField(default=True, help_text='Включить/отключить плашку подтверждения возраста', verbose_name='Показывать плашку 18+')),
                ('age_gate_title', models.CharField(default='Вам есть 18 лет?', help_text='Заголовок, отображаемый на плашке возраста', max_length=200, verbose_name='Заголовок плашки 18+')),
                ('age_gate_text', models.TextField(default='Доступ к сайту разрешён только пользователям старше 18 лет. Подтвердите возраст для продолжения работы.', help_text='Описание на плашке возраста', verbose_name='Текст плашки 18+')),
                ('site_maintenance', models.BooleanField(default=False, help_text='Включить режим технического обслуживания', verbose_name='Режим обслуживания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
