# Generated by Django 5.2 on 2025-08-31 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="purchased_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.PositiveIntegerField(default=30),
        ),
    ]

