# Generated by Django 5.2 on 2025-09-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_wallet_created_at_wallet_purchased_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
