# Generated by Cline on 2025-10-17
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[
                    ("like_photo", "Like: photo"),
                    ("like_video", "Like: video"),
                    ("comment_photo", "Comment: photo"),
                    ("comment_video", "Comment: video"),
                    ("reply_photo", "Reply: photo comment"),
                    ("reply_video", "Reply: video comment"),
                    ("comment_like_photo", "Like: photo comment"),
                    ("comment_like_video", "Like: video comment"),
                    ("follow", "New follower"),
                    ("wallet_topup", "Wallet top-up"),
                    ("recommendation", "Recommendation"),
                ], db_index=True, max_length=32)),
                ("message", models.CharField(max_length=200)),
                ("link", models.CharField(blank=True, default="", max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="notifications_sent", to=settings.AUTH_USER_MODEL)),
                ("recipient", models.ForeignKey(on_delete=models.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "is_read", "-created_at"], name="notif_rec_read_created"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "type", "-created_at"], name="notif_rec_type_created"),
        ),
    ]
