# Generated by Django 5.2.7 on 2025-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_follow"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="follow",
            new_name="dashboard_f_followe_1678a8_idx",
            old_name="dashboard_follower_idx",
        ),
        migrations.RenameIndex(
            model_name="follow",
            new_name="dashboard_f_followi_339d78_idx",
            old_name="dashboard_following_idx",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(
                default=True,
                help_text="Если True, другие видят только опубликованные работы. Если False - все завершенные работы.",
            ),
        ),
    ]
