# Generated by Django 5.2.7 on 2025-10-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_notification"),
        (
            "dashboard",
            "0007_rename_dashboard_follower_idx_dashboard_f_followe_1678a8_idx_and_more",
        ),
    ]

    operations = []
