# Generated by Django 5.2.7 on 2025-11-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_merge_20251018_1124"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="dashboard_n_recipie_91720a_idx",
            old_name="notif_rec_read_created",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="dashboard_n_recipie_457536_idx",
            old_name="notif_rec_type_created",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("like_photo", "Like: photo"),
                    ("like_video", "Like: video"),
                    ("comment_photo", "Comment: photo"),
                    ("comment_video", "Comment: video"),
                    ("reply_photo", "Reply: photo comment"),
                    ("reply_video", "Reply: video comment"),
                    ("comment_like_photo", "Like: photo comment"),
                    ("comment_like_video", "Like: video comment"),
                    ("like_job", "Like: job"),
                    ("comment_job", "Comment: job"),
                    ("reply_job", "Reply: job comment"),
                    ("comment_like_job", "Like: job comment"),
                    ("follow", "New follower"),
                    ("wallet_topup", "Wallet top-up"),
                    ("admin_message", "Admin message"),
                    ("recommendation", "Recommendation"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
