# Generated by Django 5.2 on 2025-09-14 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(upload_to="blog/covers/", verbose_name="Обложка"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Краткое описание"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст статьи")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Если пусто — берём обычный заголовок.",
                        max_length=180,
                        verbose_name="Meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Короткий SEO-описание для сниппета.",
                        max_length=300,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="OG title"
                    ),
                ),
                (
                    "og_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="OG description"
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Если пусто — используем обложку.",
                        null=True,
                        upload_to="blog/og/",
                        verbose_name="OG image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["-published_at", "-id"],
            },
        ),
    ]
