# Generated by Django 5.2 on 2025-09-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=48, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=64, unique=True, verbose_name="Слаг"),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Короткое SEO-описание для сниппета.",
                max_length=300,
                verbose_name="Meta description",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Список тегов для фильтрации и SEO.",
                related_name="posts",
                to="blog.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_published", "published_at"],
                name="blog_post_is_publ_9c4b34_idx",
            ),
        ),
    ]
