# Generated by Django 5.2 on 2025-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag_alter_post_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=200,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=64, unique=True, verbose_name="Слаг"
            ),
        ),
    ]
