# Generated by Django 5.2 on 2025-09-02 12:09

import django.db.models.deletion
import django.utils.timezone
import generate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, unique=True)),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Подсказка",
                "verbose_name_plural": "Подсказки",
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guest_session_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("prompt", models.TextField()),
                (
                    "model_id",
                    models.CharField(
                        default=generate.models.default_model_id, max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В очереди"),
                            ("RUNNING", "Обработка"),
                            ("DONE", "Готово"),
                            ("FAILED", "Ошибка"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="gen/%Y/%m/"),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("tokens_spent", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача генерации",
                "verbose_name_plural": "Задачи генерации",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="generate_ge_user_id_636048_idx",
                    ),
                    models.Index(
                        fields=["is_public", "created_at"],
                        name="generate_ge_is_publ_bd8bef_idx",
                    ),
                    models.Index(
                        fields=["guest_session_key", "created_at"],
                        name="generate_ge_guest_s_ba2a2b_idx",
                    ),
                ],
            },
        ),
    ]
