# Generated by Django 5.2 on 2025-09-07 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="last_polled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="provider_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="provider_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="provider_task_uuid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["status", "created_at"], name="generate_ge_status_c2f321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["provider_task_uuid"], name="generate_ge_provide_73bf6a_idx"
            ),
        ),
    ]
