# Generated by Django 5.2 on 2025-09-12 20:34

import django.db.models.deletion
import generate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0003_freegrant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Слаг"),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Категория примеров",
                "verbose_name_plural": "Категории примеров",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ShowcaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="showcase/%Y/%m/")),
                ("title", models.CharField(max_length=140)),
                ("prompt", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Пример изображения",
                "verbose_name_plural": "Примеры изображений",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SuggestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Слаг"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Описание"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Категория подсказок",
                "verbose_name_plural": "Категории подсказок",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AlterModelOptions(
            name="freegrant",
            options={
                "verbose_name": "Гостевая квота",
                "verbose_name_plural": "Гостевые квоты",
            },
        ),
        migrations.AddField(
            model_name="suggestion",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="fp",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="total",
            field=models.PositiveIntegerField(
                default=generate.models.guest_initial_tokens
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="text",
            field=models.TextField(verbose_name="Текст подсказки"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="title",
            field=models.CharField(
                max_length=80, unique=True, verbose_name="Заголовок"
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(fields=["gid"], name="generate_fr_gid_119d87_idx"),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(
                fields=["created_at"], name="generate_fr_created_6573bb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="freegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="freegrant_total_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="freegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumed__gte", 0)),
                name="freegrant_consumed_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="freegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("consumed__lte", models.F("total"))),
                name="freegrant_consumed_lte_total",
            ),
        ),
        migrations.AddField(
            model_name="showcaseimage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="generate.showcasecategory",
            ),
        ),
        migrations.AddField(
            model_name="showcaseimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_showcase_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to="generate.suggestioncategory",
                verbose_name="Категория",
            ),
        ),
    ]
