# Generated by Django 5.2 on 2025-09-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0002_seed_suggestions"),
        ("generate", "0004_showcasecategory_showcaseimage_suggestioncategory_and_more"),
    ]

    operations = []
