# Generated by Django 5.2 on 2025-09-20 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0005_merge_20250914_0944"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="freegrant",
            name="ip_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="freegrant",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="freegrant",
            name="ua_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(
                fields=["session_key"], name="generate_fr_session_ea99e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(
                fields=["ip_hash"], name="generate_fr_ip_hash_c12627_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(
                fields=["ua_hash"], name="generate_fr_ua_hash_8dfe84_idx"
            ),
        ),
    ]
