# Generated by Django 5.2 on 2025-09-20 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0006_freegrant_ip_hash_freegrant_session_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="guest_fp",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="guest_gid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["guest_gid", "created_at"],
                name="generate_ge_guest_g_ad262e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["guest_fp", "created_at"], name="generate_ge_guest_f_87545d_idx"
            ),
        ),
    ]
