# Generated by Django 5.2 on 2025-09-21 15:42

import django.db.models.deletion
import generate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0007_generationjob_guest_fp_generationjob_guest_gid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbuseCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_jobs_limit",
                    models.PositiveIntegerField(
                        default=generate.models.abuse_guest_jobs_limit
                    ),
                ),
                ("guest_jobs_used", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
            ],
            options={
                "verbose_name": "Анти-абуз кластер",
                "verbose_name_plural": "Анти-абуз кластеры",
            },
        ),
        migrations.CreateModel(
            name="AbuseIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fp", "Fingerprint"),
                            ("gid", "Cookie GID"),
                            ("ip", "IP hash"),
                            ("ua", "UA hash"),
                            ("user", "User ID"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=128)),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Анти-абуз идентификатор",
                "verbose_name_plural": "Анти-абуз идентификаторы",
            },
        ),
        migrations.AddField(
            model_name="freegrant",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grants",
                to="generate.abusecluster",
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="generate.abusecluster",
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(
                fields=["cluster", "created_at"], name="generate_fr_cluster_97be4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generationjob",
            index=models.Index(
                fields=["cluster", "created_at"], name="generate_ge_cluster_0a6990_idx"
            ),
        ),
        migrations.AddField(
            model_name="abuseidentifier",
            name="cluster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="generate.abusecluster",
            ),
        ),
        migrations.AddIndex(
            model_name="abuseidentifier",
            index=models.Index(
                fields=["kind", "value"], name="generate_ab_kind_fb1a66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abuseidentifier",
            index=models.Index(
                fields=["cluster", "kind"], name="generate_ab_cluster_fbb3b5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="abuseidentifier",
            constraint=models.UniqueConstraint(
                fields=("kind", "value"), name="uq_abuse_identifier_kind_value"
            ),
        ),
    ]
