# Generated by Django 5.2 on 2025-09-21 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0008_abusecluster_abuseidentifier_freegrant_cluster_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="freegrant",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="freegrant",
            name="freegrant_total_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="freegrant",
            name="freegrant_consumed_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="freegrant",
            name="freegrant_consumed_lte_total",
        ),
        migrations.RemoveIndex(
            model_name="freegrant",
            name="generate_fr_created_6573bb_idx",
        ),
        migrations.RemoveIndex(
            model_name="freegrant",
            name="generate_fr_session_ea99e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="freegrant",
            name="generate_fr_cluster_97be4d_idx",
        ),
        migrations.RemoveField(
            model_name="freegrant",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="freegrant",
            name="session_key",
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="fp",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="gid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="total",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="freegrant",
            index=models.Index(fields=["fp"], name="generate_fr_fp_db5aa7_idx"),
        ),
    ]
