# Generated by Django 5.2 on 2025-09-21 18:09

import generate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0009_alter_freegrant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freegrant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="freegrant",
            name="total",
            field=models.PositiveIntegerField(
                default=generate.models.guest_initial_tokens
            ),
        ),
    ]
