# Generated by Django 5.2.6 on 2025-10-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0010_alter_freegrant_created_at_alter_freegrant_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В очереди'), ('RUNNING', 'Обработка'), ('DONE', 'Готово'), ('FAILED', 'Ошибка'), ('PENDING_MODERATION', 'Ожидает модерации')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
