# Generated by Django 5.2.6 on 2025-10-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0011_alter_generationjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="original_prompt",
            field=models.TextField(
                blank=True, default="", help_text="Оригинальный промпт до перевода"
            ),
        ),
    ]
