# Generated by Django 5.2.6 on 2025-10-11 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0012_generationjob_original_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseAdditionalImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="showcase/%Y/%m/additional/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "showcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="generate.showcaseimage",
                        verbose_name="Пример",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное изображение",
                "verbose_name_plural": "Дополнительные изображения",
                "ordering": ("order", "created_at"),
            },
        ),
    ]
