# Generated by Django 5.2.6 on 2025-10-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0012_seed_prompt_categories"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="categoryprompt",
            new_name="generate_ca_categor_cd3690_idx",
            old_name="gen_cprompt_cat_active_idx",
        ),
        migrations.RenameIndex(
            model_name="promptcategory",
            new_name="generate_pr_is_acti_3106a4_idx",
            old_name="gen_pcat_active_order_idx",
        ),
    ]
