# Generated migration for filling remaining professional English prompts - Part 2

from django.db import migrations


def fill_english_prompts_part2(apps, schema_editor):
    """Заполняет оставшиеся поля prompt_en профессиональными английскими промптами"""
    CategoryPrompt = apps.get_model('generate', 'CategoryPrompt')
    
    # Словарь: русский текст -> профессиональный английский промпт
    prompts_mapping = {
        # Будущее (продолжение)
        "Искусственный интеллект, сознание, этика": "Artificial intelligence consciousness, ethical AI, sentient machine, digital mind, futuristic concept art, glowing neural pathways, philosophical questions, sci-fi illustration, technological singularity",
        "Экологичный город, зелень, устойчивость": "Eco-friendly city, vertical gardens, sustainable architecture, green urban planning, renewable energy, futuristic ecology, professional concept art, nature integration, clean technology",
        "Космический лифт, орбита, инженерия": "Space elevator, orbital tether, engineering marvel, futuristic infrastructure, Earth to orbit, sci-fi megastructure, professional concept art, advanced materials, space access",
        "Квантовый компьютер, вычисления, прорыв": "Quantum computer, advanced computing, qubits visualization, scientific breakthrough, futuristic technology, professional photography, complex calculations, technological revolution, glowing processors",
        
        # Винтаж (продолжение)
        "Старая фотография, сепия, ностальгия": "Vintage sepia photograph, aged paper texture, nostalgic atmosphere, antique photo, warm brown tones, historical memory, classic photography, timeless moment, retro aesthetic",
        "Винтажный автомобиль, ретро, классика": "Classic vintage car, retro automobile, chrome details, pristine restoration, 1950s styling, automotive heritage, professional car photography, nostalgic beauty, timeless design",
        "Старинная мебель, антиквариат, история": "Antique furniture, vintage craftsmanship, historical pieces, ornate details, aged wood, classic design, professional photography, timeless elegance, heritage quality",
        "Ретро кафе, 50-е годы, атмосфера": "1950s retro diner, vintage café interior, checkered floor, chrome fixtures, nostalgic ambiance, classic Americana, warm lighting, period atmosphere, timeless charm",
        "Винтажная камера, фотография, ностальгия": "Vintage camera, classic photography equipment, retro technology, mechanical precision, nostalgic aesthetic, professional product shot, timeless design, analog photography",
        "Старые книги, библиотека, знания": "Antique books, vintage library, leather bindings, aged pages, scholarly atmosphere, classical knowledge, warm lighting, literary heritage, timeless wisdom",
        "Граммофон, музыка, ретро, звук": "Vintage gramophone, antique music player, brass horn, vinyl records, nostalgic sound, retro technology, warm ambient light, classic design, musical heritage",
        "Винтажная одежда, мода, стиль": "Vintage clothing, retro fashion, classic style, period garments, nostalgic aesthetic, professional fashion photography, timeless elegance, authentic vintage",
        "Старинные часы, время, механизм": "Antique timepiece, vintage clock, mechanical movement, intricate gears, classic craftsmanship, professional photography, timeless design, precision engineering",
        "Ретро постер, графика, дизайн": "Vintage poster, retro graphic design, classic typography, aged paper, nostalgic advertising, bold colors, Art Deco style, collectible art",
        "Винтажная посуда, чай, уют": "Vintage china, antique teacups, classic patterns, nostalgic tea time, elegant tableware, warm atmosphere, professional photography, timeless elegance",
        "Старая пишущая машинка, литература": "Antique typewriter, vintage writing machine, mechanical keys, literary nostalgia, classic office, warm sepia tones, professional photography, timeless craftsmanship",
        "Ретро телефон, связь, ностальгия": "Vintage rotary phone, retro telephone, classic communication, nostalgic technology, period piece, warm colors, professional product shot, timeless design",
        "Винтажные украшения, элегантность": "Vintage jewelry, antique accessories, classic elegance, precious gems, timeless beauty, professional photography, ornate details, heritage craftsmanship",
        "Старинная карта, путешествия, история": "Antique map, vintage cartography, aged parchment, historical exploration, classic navigation, warm sepia tones, professional photography, timeless adventure",
        
        # Времена года
        "Весна, цветущие деревья, свежесть, обновление": "Spring season, blooming trees, fresh atmosphere, renewal energy, cherry blossoms, vibrant colors, professional landscape photography, natural awakening, seasonal beauty",
        "Лето, пляж, солнце, отдых, тепло": "Summer beach scene, bright sunshine, vacation atmosphere, warm weather, sandy shore, ocean waves, professional photography, relaxation vibes, seasonal joy",
        "Осень, золотые листья, урожай, уют": "Autumn foliage, golden leaves, harvest season, cozy atmosphere, fall colors, professional landscape photography, seasonal transformation, warm tones",
        "Зима, снег, мороз, сказка, белизна": "Winter wonderland, fresh snow, frost patterns, fairy tale atmosphere, white landscape, professional photography, magical season, pristine beauty",
        "Ранняя весна, первые цветы, пробуждение": "Early spring, first flowers blooming, nature awakening, fresh growth, delicate blossoms, professional nature photography, seasonal rebirth, gentle colors",
        "Жаркое лето, зной, яркое солнце": "Hot summer day, intense heat, blazing sun, warm atmosphere, summer vibes, professional photography, bright light, seasonal intensity",
        "Поздняя осень, дождь, меланхолия": "Late autumn, rainy weather, melancholic mood, falling leaves, grey skies, professional photography, seasonal transition, atmospheric beauty",
        "Снежная зима, метель, холод": "Snowy winter, blizzard conditions, cold weather, heavy snowfall, professional photography, harsh beauty, winter storm, dramatic atmosphere",
        "Весенний дождь, свежесть, зелень": "Spring rain, fresh greenery, nature refreshed, rain droplets, vibrant vegetation, professional photography, seasonal renewal, clean atmosphere",
        "Летний закат, теплые краски, романтика": "Summer sunset, warm colors, romantic atmosphere, golden hour, beach scene, professional landscape photography, peaceful evening, seasonal beauty",
        "Осенний туман, загадочность, тишина": "Autumn fog, mysterious atmosphere, quiet morning, misty landscape, professional photography, ethereal beauty, seasonal mood, peaceful silence",
        "Зимнее утро, иней, морозные узоры": "Winter morning, frost patterns, ice crystals, frozen beauty, professional macro photography, delicate details, seasonal magic, pristine nature",
        "Майские грозы, весна, энергия": "May thunderstorms, spring energy, dramatic clouds, lightning strikes, professional photography, powerful nature, seasonal drama, atmospheric intensity",
        "Бабье лето, тепло, золото": "Indian summer, warm autumn days, golden light, late season warmth, professional photography, peaceful atmosphere, seasonal gift, gentle beauty",
        "Первый снег, зима, чистота": "First snowfall, winter arrival, pristine white, fresh snow, professional photography, magical moment, seasonal transition, pure beauty",
        
        # Города (продолжение)
        "Нью-Йорк, Таймс-сквер, небоскребы, огни": "New York Times Square, towering skyscrapers, bright billboards, urban energy, night lights, professional cityscape photography, iconic landmark, vibrant atmosphere, 8K ultra detailed",
        "Париж, Эйфелева башня, романтика, закат": "Paris Eiffel Tower, romantic sunset, golden hour, French landmark, Seine River, professional travel photography, European elegance, iconic monument, dreamy atmosphere",
        "Токио, неоновые вывески, ночь, киберпанк": "Tokyo night scene, neon signs, cyberpunk aesthetic, Japanese street, urban energy, professional cityscape photography, futuristic atmosphere, vibrant lights, 8K detailed",
        "Венеция, каналы, гондолы, архитектура": "Venice canals, traditional gondolas, Italian architecture, romantic waterways, historic buildings, professional travel photography, European charm, cultural heritage, picturesque scene",
        "Лондон, Биг-Бен, туман, классика": "London Big Ben, atmospheric fog, classic landmark, Thames River, Gothic architecture, professional cityscape photography, British heritage, moody weather, iconic view",
        "Дубай, небоскребы, роскошь, современность": "Dubai skyline, luxury skyscrapers, modern architecture, Burj Khalifa, futuristic cityscape, professional photography, opulent development, 8K ultra HD, architectural marvel",
        "Прага, старый город, средневековье, уют": "Prague Old Town, medieval architecture, historic center, cobblestone streets, European heritage, professional travel photography, Gothic buildings, charming atmosphere, cultural landmark",
        "Сидней, оперный театр, гавань, архитектура": "Sydney Opera House, harbor view, iconic architecture, waterfront cityscape, Australian landmark, professional photography, modern design, cultural icon, stunning location",
        "Барселона, Гауди, Саграда Фамилия, искусство": "Barcelona Sagrada Familia, Gaudi architecture, modernist masterpiece, artistic details, Spanish culture, professional photography, architectural wonder, colorful mosaics, cultural treasure",
        "Амстердам, каналы, велосипеды, мосты": "Amsterdam canals, Dutch architecture, bicycles everywhere, canal bridges, European charm, professional travel photography, colorful buildings, peaceful waterways, cultural scene",
        "Рим, Колизей, древность, история": "Rome Colosseum, ancient architecture, historical landmark, Roman Empire, archaeological wonder, professional photography, cultural heritage, dramatic sky, epic monument",
        "Сан-Франциско, мост Золотые Ворота, туман": "San Francisco Golden Gate Bridge, fog rolling in, iconic landmark, Pacific Ocean, suspension bridge, professional photography, California coastline, dramatic atmosphere, engineering marvel",
        "Стамбул, мечети, Босфор, культура": "Istanbul mosques, Bosphorus strait, Ottoman architecture, cultural fusion, Eastern heritage, professional photography, Blue Mosque, Turkish culture, historic cityscape",
        "Рио-де-Жанейро, статуя Христа, пляжи": "Rio de Janeiro, Christ the Redeemer, Copacabana beach, Brazilian culture, tropical paradise, professional photography, iconic landmark, vibrant atmosphere, coastal beauty",
        "Москва, Красная площадь, Кремль, история": "Moscow Red Square, Kremlin walls, St Basil's Cathedral, Russian heritage, historic landmark, professional photography, cultural center, architectural beauty, iconic view",
        
        # Детство
        "Ребенок играет, радость, беззаботность": "Child playing, joyful expression, carefree moment, natural happiness, outdoor activity, professional photography, innocent fun, candid shot, heartwarming scene",
        "Детская площадка, качели, веселье": "Children's playground, swing set, playful fun, outdoor recreation, sunny day, professional photography, childhood joy, active play, happy moments",
        "Игрушки, детство, воспоминания, ностальгия": "Childhood toys, nostalgic memories, vintage playthings, sentimental objects, warm lighting, professional photography, innocent times, treasured moments, emotional connection",
        "Ребенок рисует, творчество, фантазия": "Child drawing, creative expression, artistic imagination, colorful crayons, focused concentration, professional photography, childhood creativity, innocent art, developmental moment",
        "Детский день рождения, торт, праздник": "Children's birthday party, celebration cake, festive decorations, joyful gathering, colorful balloons, professional photography, happy celebration, childhood milestone, party atmosphere",
        "Ребенок с мыльными пузырями, игра, радость": "Child with soap bubbles, playful moment, magical wonder, outdoor fun, floating bubbles, professional photography, innocent joy, dreamy atmosphere, childhood magic",
        "Детская комната, игрушки, уют": "Children's bedroom, toys scattered, cozy atmosphere, playful space, colorful decor, professional interior photography, childhood sanctuary, comfortable setting, warm lighting",
        "Ребенок читает книгу, знания, воображение": "Child reading book, learning moment, imaginative journey, focused expression, educational activity, professional photography, intellectual development, peaceful scene, childhood wonder",
        "Дети бегут по полю, свобода, счастье": "Children running in field, carefree freedom, joyful happiness, outdoor play, natural setting, professional photography, innocent energy, summer day, pure joy",
        "Ребенок с домашним питомцем, дружба": "Child with pet, loving friendship, tender moment, animal bond, heartwarming interaction, professional photography, emotional connection, innocent love, companionship",
        "Детские рисунки, творчество, фантазия": "Children's drawings, creative artwork, imaginative expression, colorful creations, artistic development, professional photography, innocent art, childhood imagination, developmental milestone",
        "Ребенок на велосипеде, обучение, радость": "Child learning bicycle, training wheels, joyful achievement, outdoor activity, developmental milestone, professional photography, childhood accomplishment, proud moment, active play",
        "Детский сад, игры, общение": "Kindergarten, children playing, social interaction, educational environment, group activities, professional photography, childhood development, learning through play, happy atmosphere",
        "Ребенок строит из кубиков, развитие": "Child building blocks, developmental play, creative construction, focused concentration, educational toy, professional photography, cognitive development, problem solving, childhood learning",
        "Детские воспоминания, ностальгия, тепло": "Childhood memories, nostalgic warmth, sentimental moments, treasured past, emotional connection, professional photography, innocent times, heartfelt nostalgia, precious memories",
        
        # Для разработки
        "Современный офис разработчиков, мониторы с кодом, минималистичный дизайн": "Modern developer office, multiple monitors displaying code, minimalist workspace design, clean aesthetic, professional tech environment, contemporary furniture, coding atmosphere, 8K detailed, productive space",
        "Абстрактная визуализация данных, графики, синий неоновый свет": "Abstract data visualization, analytical graphs, blue neon lighting, digital dashboard, professional infographic, modern UI design, tech aesthetic, glowing elements, futuristic display",
        "Рабочее место программиста, несколько мониторов, темная тема IDE": "Programmer workspace, multi-monitor setup, dark theme IDE, coding environment, professional desk, modern technology, developer tools, clean organization, productive atmosphere",
        "Серверная комната, ряды серверов, синие индикаторы": "Server room, rack-mounted servers, blue LED indicators, data center, professional IT infrastructure, cooling systems, network equipment, technological backbone, organized cables",
        "Концепт искусственного интеллекта, нейронные сети, футуристичный стиль": "AI concept visualization, neural network architecture, futuristic design, machine learning, digital brain, professional illustration, glowing connections, technological innovation, sci-fi aesthetic",
        "Кибербезопасность, цифровой замок, защищенные данные": "Cybersecurity concept, digital lock, encrypted data, network protection, professional illustration, secure systems, firewall visualization, tech security, modern defense",
        "Облачные технологии, абстрактное облако из данных": "Cloud computing, abstract data cloud, network infrastructure, professional tech illustration, distributed systems, modern technology, digital transformation, scalable architecture",
        "Мобильная разработка, смартфон с интерфейсом приложения": "Mobile app development, smartphone interface, UI/UX design, modern application, professional product shot, clean design, user experience, contemporary technology",
        "DevOps концепт, CI/CD pipeline, автоматизация": "DevOps concept, CI/CD pipeline visualization, automation workflow, professional diagram, modern development, continuous integration, deployment process, tech efficiency",
        "Блокчейн визуализация, цепочка блоков, криптография": "Blockchain visualization, chain of blocks, cryptographic security, distributed ledger, professional illustration, decentralized network, modern technology, digital trust",
        "Квантовые вычисления, абстрактные кубиты": "Quantum computing, qubit visualization, superposition states, professional scientific illustration, advanced technology, quantum mechanics, futuristic computing, complex systems",
        "IoT устройства, умный дом, подключенные гаджеты": "IoT devices, smart home ecosystem, connected gadgets, modern automation, professional photography, wireless network, intelligent systems, contemporary living",
        "Виртуальная реальность, VR шлем, цифровой мир": "Virtual reality headset, VR technology, digital immersion, futuristic gaming, professional product photography, immersive experience, modern entertainment, cutting-edge device",
        "Машинное обучение, алгоритмы, визуализация данных": "Machine learning algorithms, data visualization, AI training, professional illustration, neural networks, pattern recognition, modern technology, computational intelligence",
        "Кодинг на ноутбуке в кафе, программист за работой": "Coding in café, laptop programming, developer lifestyle, remote work, professional photography, modern workspace, digital nomad, productive atmosphere, contemporary work culture",
        
        # Еда (продолжение)
        "Изысканный десерт, макарон, французская кондитерская": "Gourmet French macarons, elegant pastry, fine confectionery, colorful dessert, professional food photography, delicate texture, Parisian bakery, culinary artistry, premium quality",
        "Свежие фрукты, яркие цвета, капли воды": "Fresh fruit display, vibrant colors, water droplets, natural produce, professional food photography, healthy eating, organic freshness, appetizing presentation, colorful arrangement",
        "Итальянская паста, томатный соус, базилик": "Italian pasta dish, rich tomato sauce, fresh basil, authentic cuisine, professional food photography, al dente perfection, rustic presentation, culinary tradition, appetizing close-up",
        "Суши сет, японская кухня, минимализм": "Sushi platter, Japanese cuisine, minimalist presentation, fresh fish, elegant plating, professional food photography, authentic preparation, cultural tradition, clean aesthetic",
        "Завтрак в постель, круассаны, кофе, уют": "Breakfast in bed, fresh croissants, aromatic coffee, cozy morning, professional lifestyle photography, romantic gesture, comfortable setting, warm atmosphere, indulgent treat",
        "Барбекю, мясо на гриле, дым, аппетитная корочка": "BBQ grilling, smoky meat, charred crust, outdoor cooking, professional food photography, appetizing texture, summer gathering, rustic presentation, mouth-watering details",
        "Свежая выпечка, хлеб, ароматный пар": "Fresh baked bread, artisan bakery, aromatic steam, golden crust, professional food photography, warm from oven, rustic presentation, homemade quality, inviting aroma",
        "Тропические коктейли, яркие цвета, фрукты": "Tropical cocktails, vibrant colors, fresh fruit garnish, exotic drinks, professional beverage photography, beach vibes, colorful presentation, vacation atmosphere, refreshing appeal",
        "Шоколадный торт, глазурь, декор": "Chocolate cake, rich frosting, elegant decoration, gourmet dessert, professional food photography, indulgent treat, layered perfection, culinary artistry, premium quality",
        "Овощной салат, свежесть, здоровое питание": "Fresh vegetable salad, healthy eating, crisp greens, colorful ingredients, professional food photography, nutritious meal, organic produce, clean eating, appetizing presentation",
        "Стейк с кровью, ресторанная подача": "Medium-rare steak, restaurant plating, juicy meat, professional food photography, gourmet presentation, culinary excellence, fine dining, appetizing details, Michelin quality",
        "Мороженое, разные вкусы, вафельный рожок": "Ice cream cone, multiple flavors, waffle cone, colorful scoops, professional food photography, summer treat, creamy texture, sweet indulgence, appetizing presentation",
        "Пицца, расплавленный сыр, итальянская кухня": "Artisan pizza, melted cheese, Italian cuisine, fresh toppings, professional food photography, wood-fired oven, authentic recipe, appetizing close-up, culinary tradition",
        "Морепродукты, лобстер, изысканная подача": "Seafood platter, fresh lobster, gourmet presentation, ocean delicacies, professional food photography, luxury dining, elegant plating, culinary excellence, premium quality",
        "Кофе латте-арт, пенка, узор": "Latte art coffee, foam design, barista skill, café atmosphere, professional beverage photography, artistic presentation, aromatic brew, contemporary coffee culture, detailed craftsmanship",
        
        # Животные (продолжение)
        "Величественный лев в саванне, золотой час": "Majestic lion in savanna, golden hour lighting, African wildlife, powerful predator, professional nature photography, natural habitat, regal presence, 8K ultra detailed, National Geographic quality",
        "Белый медведь на льдине, арктический пейзаж": "Polar bear on ice floe, Arctic landscape, endangered species, frozen wilderness, professional wildlife photography, climate documentation, natural habitat, powerful animal, pristine environment",
        "Тропические птицы, яркое оперение, джунгли": "Tropical birds, vibrant plumage, jungle habitat, exotic species, professional wildlife photography, colorful feathers, natural beauty, rainforest biodiversity, stunning colors",
        "Дельфины в океане, прыжок из воды, брызги": "Dolphins jumping, ocean spray, marine mammals, playful behavior, professional wildlife photography, dynamic action, natural grace, crystal clear water, joyful creatures",
        "Лошадь на галопе, грива развевается, динамика": "Horse galloping, flowing mane, dynamic motion, powerful stride, professional equine photography, athletic beauty, natural movement, muscular grace, outdoor setting",
        "Панда ест бамбук, милое выражение, природа": "Giant panda eating bamboo, adorable expression, endangered species, natural habitat, professional wildlife photography, conservation icon, peaceful moment, black and white fur",
        "Волк воет на луну, зимний лес, драматизм": "Wolf howling at moon, winter forest, dramatic scene, wild nature, professional wildlife photography, atmospheric lighting, powerful predator, mystical moment, untamed beauty",
        "Колибри у цветка, макросъемка, детали": "Hummingbird at flower, macro photography, hovering motion, iridescent feathers, professional wildlife shot, nectar feeding, vibrant colors, frozen action, detailed wings",
        "Слон с слоненком, семейная сцена, саванна": "Elephant with calf, family bond, African savanna, maternal care, professional wildlife photography, emotional moment, natural habitat, gentle giants, heartwarming scene",
        "Кот в уютном интерьере, домашний питомец": "Cat in cozy interior, domestic pet, comfortable home, feline grace, professional pet photography, warm atmosphere, relaxed pose, charming companion, lifestyle shot",
        "Орел в полете, размах крыльев, небо": "Eagle soaring, wings spread wide, mountain backdrop, freedom symbol, professional wildlife photography, powerful flight, majestic bird, dramatic sky, 8K ultra sharp",
        "Морская черепаха под водой, коралловый риф": "Sea turtle swimming, coral reef, underwater photography, marine conservation, professional wildlife shot, graceful movement, ocean life, crystal clear water, natural behavior",
        "Лиса в осеннем лесу, рыжая шерсть, листья": "Fox in autumn forest, red fur, fall foliage, wild nature, professional wildlife photography, natural camouflage, seasonal beauty, cunning predator, atmospheric scene",
        "Жираф на закате, силуэт, африканский пейзаж": "Giraffe at sunset, silhouette, African landscape, acacia trees, professional wildlife photography, golden hour, savanna beauty, tall stature, iconic scene",
        "Бабочка на цветке, макро, яркие краски": "Butterfly on flower, macro photography, vibrant colors, delicate wings, professional nature shot, natural beauty, detailed close-up, soft natural light, spring scene",
        
        # Интерьер (продолжение)
        "Современная гостиная, минимализм, светлые тона": "Modern minimalist living room, light color palette, clean lines, contemporary furniture, professional interior photography, open space, Scandinavian design, natural light, 8K detailed",
        "Уютная спальня, мягкое освещение, комфорт": "Cozy bedroom, soft ambient lighting, comfortable bedding, warm atmosphere, professional interior photography, peaceful sanctuary, inviting space, relaxing environment, lifestyle shot",
        "Кухня в скандинавском стиле, белый цвет, дерево": "Scandinavian kitchen, white cabinets, wooden accents, minimalist design, professional interior photography, natural light, functional layout, Nordic aesthetic, clean lines",
        "Домашний офис, рабочее место, организация": "Home office workspace, organized desk, ergonomic setup, professional interior photography, productive environment, modern furniture, natural lighting, minimalist aesthetic, inspiring space",
        "Ванная комната, мрамор, роскошь": "Luxury bathroom, marble surfaces, spa atmosphere, elegant fixtures, professional interior photography, hotel quality, modern design, relaxing environment, premium materials",
        "Детская комната, яркие цвета, игрушки": "Colorful children's room, bright colors, playful design, toy storage, professional interior photography, fun atmosphere, kid-friendly space, organized chaos, cheerful environment",
        "Лофт интерьер, кирпич, высокие потолки": "Industrial loft interior, exposed brick walls, high ceilings, urban aesthetic, professional interior photography, open floor plan, modern furniture, contemporary design, raw materials",
        "Классический интерьер, антикварная мебель": "Classic interior design, antique furniture, traditional elegance, ornate details, professional interior photography, timeless style, luxury materials, sophisticated atmosphere, heritage quality",
        "Эко-интерьер, натуральные материалы, растения": "Eco-friendly interior, natural materials, indoor plants, sustainable design, professional interior photography, green living, organic textures, biophilic design, healthy environment",
        "Футуристический интерьер, технологии, свет": "Futuristic interior, advanced technology, LED lighting, modern design, professional interior photography, smart home, innovative materials, sci-fi aesthetic, cutting-edge style",
        "Библиотека, книжные полки, уют": "Home library, floor-to-ceiling bookshelves, cozy reading nook, warm lighting, professional interior photography, literary sanctuary, comfortable seating, intellectual space, peaceful atmosphere",
        "Домашний кинотеатр, комфорт, технологии": "Home theater room, comfortable seating, advanced audio-visual, professional interior photography, entertainment space, modern technology, cinematic experience, luxury amenity, immersive environment",
        "Зимний сад, растения, стекло": "Indoor winter garden, lush plants, glass walls, botanical sanctuary, professional interior photography, natural light, green oasis, peaceful atmosphere, nature integration",
        "Винный погреб, деревянные стеллажи": "Wine cellar, wooden racks, bottle collection, professional interior photography, temperature controlled, luxury storage, sophisticated space, connoisseur's dream, elegant organization",
        "Арт-студия, творческое пространство, свет": "Art studio, creative workspace, natural lighting, artistic environment, professional interior photography, inspiring space, organized chaos, painter's sanctuary, creative freedom",
        
        # Искусство
        "Художник за мольбертом, масляные краски, творчество": "Artist at easel, oil painting, creative process, professional photography, artistic expression, studio atmosphere, colorful palette, passionate work, cultural documentation",
        "Скульптура из мрамора, классическое искусство": "Marble sculpture, classical art, carved stone, Renaissance style, professional photography, timeless beauty, artistic mastery, museum quality, cultural heritage",
        "Граффити на стене, уличное искусство, яркость": "Street art graffiti, urban wall mural, vibrant colors, contemporary expression, professional photography, public art, bold statement, cultural movement, creative rebellion",
        "Акварельный пейзаж, мягкие переходы, нежность": "Watercolor landscape, soft color transitions, gentle brushwork, artistic painting, professional photography, delicate technique, flowing pigments, ethereal beauty, traditional medium",
        "Керамика, гончарный круг, ручная работа": "Pottery making, potter's wheel, handcrafted ceramics, artisan work, professional photography, clay shaping, traditional craft, creative process, skilled hands",
        "Витраж, цветное стекло, свет": "Stained glass window, colored glass art, light filtering through, Gothic architecture, professional photography, religious art, vibrant colors, traditional craft, luminous beauty",
        "Каллиграфия, красивые буквы, искусство письма": "Calligraphy art, beautiful lettering, elegant script, ink and pen, professional photography, traditional writing, artistic expression, precise strokes, cultural heritage",
        "Мозаика, мелкие детали, узор": "Mosaic art, intricate details, tile pattern, Byzantine style, professional photography, colorful composition, ancient technique, patient craftsmanship, decorative beauty",
        "Фотография, камера, момент, искусство": "Photography art, camera equipment, captured moment, artistic vision, professional photography, creative expression, technical skill, visual storytelling, cultural documentation",
        "Танец, движение, грация, выражение": "Dance performance, graceful movement, artistic expression, professional photography, fluid motion, emotional storytelling, choreographed beauty, cultural art, dynamic composition",
        "Театральная сцена, актеры, драма": "Theater stage, dramatic performance, actors in character, professional photography, theatrical lighting, cultural event, artistic expression, live performance, emotional intensity",
        "Музыкальный инструмент, звук, мелодия": "Musical instrument, sound creation, melodic beauty, professional photography, artistic craftsmanship, cultural heritage, acoustic perfection, detailed close-up, musical artistry",
        "Оригами, бумага, японское искусство": "Origami art, paper folding, Japanese tradition, geometric precision, professional photography, delicate craftsmanship, cultural heritage, minimalist beauty, patient artistry",
        "Батик, ткань, роспись, узоры": "Batik fabric art, hand-painted textile, traditional patterns, wax-resist dyeing, professional photography, cultural craft, vibrant colors, Indonesian heritage, artistic technique",
        "Ювелирное искусство, драгоценности, мастерство": "Jewelry artistry, precious gems, master craftsmanship, luxury accessories, professional photography, intricate details, elegant design, valuable art, refined beauty",
        
        # История
        "Средневековый замок, рыцари, история": "Medieval castle, knights in armor, historical fortress, stone walls, professional photography, Gothic architecture, cultural heritage, dramatic sky, epic atmosphere",
        "Древний Рим, колизей, гладиаторы": "Ancient Rome, Colosseum arena, gladiator combat, historical landmark, professional photography, Roman Empire, archaeological wonder, cultural heritage, epic scale",
        "Египетские пирамиды, фараоны, древность": "Egyptian pyramids, pharaoh tombs, ancient civilization, desert landscape, professional photography, archaeological wonder, cultural heritage, monumental architecture, timeless mystery",
        "Викинги, драккар, северные воины": "Viking warriors, longship vessel, Norse culture, historical reenactment, professional photography, Scandinavian heritage, maritime tradition, fierce warriors, epic adventure",
        "Самураи, Япония, кодекс чести": "Samurai warriors, Japanese tradition, bushido code, historical armor, professional photography, cultural heritage, martial discipline, feudal Japan, honorable warriors",
        "Ренессанс, искусство, Флоренция": "Renaissance period, Florentine art, cultural rebirth, classical beauty, professional photography, Italian heritage, artistic golden age, architectural splendor, cultural revolution",
        "Дикий Запад, ковбои, прерии": "Wild West, cowboys, prairie landscape, frontier life, professional photography, American heritage, rugged individualism, historical period, western adventure",
        "Первая мировая война, окопы, история": "World War I, trench warfare, historical conflict, soldiers, professional photography, military history, dramatic atmosphere, cultural memory, somber documentation",
        "Древняя Греция, философы, Афины": "Ancient Greece, philosophers, Athens cityscape, classical civilization, professional photography, cultural heritage, intellectual tradition, marble columns, democratic birthplace",
        "Индейцы, вигвам, традиции": "Native Americans, traditional tepee, indigenous culture, tribal heritage, professional photography, cultural traditions, natural lifestyle, historical documentation, spiritual connection",
        "Пираты, корабль, сокровища, приключения": "Pirates, sailing ship, treasure hunt, maritime adventure, professional photography, golden age of piracy, nautical heritage, swashbuckling romance, historical fantasy",
        "Промышленная революция, фабрики, прогресс": "Industrial Revolution, factory machinery, technological progress, steam power, professional photography, historical transformation, urban development, mechanical innovation, societal change",
        "Холодная война, противостояние, эпоха": "Cold War era, ideological conflict, historical tension, divided world, professional photography, political standoff, cultural memory, nuclear age, superpower rivalry",
        "Великие географические открытия, корабли": "Age of Discovery, exploration ships, maritime adventure, historical voyages, professional photography, nautical heritage, world exploration, cultural exchange, brave navigators",
        "Французская революция, свобода, борьба": "French Revolution, liberty struggle, historical uprising, revolutionary spirit, professional photography, cultural transformation, political change, dramatic period, social justice",
        
        # Космос (продолжение)
        "Туманность, яркие цвета, звезды, космос": "Colorful nebula, vibrant cosmic clouds, star formation, deep space photography, astronomical wonder, professional astrophotography, celestial nursery, 8K ultra detailed, Hubble quality",
        "Планета Земля из космоса, голубая планета": "Earth from space, blue marble planet, cloud formations, orbital view, professional space photography, continents visible, atmospheric glow, cosmic perspective, NASA quality",
        "Черная дыра, гравитация, искажение пространства": "Black hole visualization, gravitational lensing, space-time distortion, event horizon, professional scientific illustration, cosmic phenomenon, accretion disk, theoretical physics, astronomical art",
        "Космическая станция, орбита, технологии": "Space station, orbital laboratory, advanced technology, Earth backdrop, professional space photography, human achievement, scientific research, zero gravity, cosmic outpost",
        "Марсианский пейзаж, красная планета, колония": "Mars landscape, red planet surface, future colony, rocky terrain, professional space photography, space exploration, alien world, human settlement, planetary colonization",
        "Кольца Сатурна, планета-гигант, космическая красота": "Saturn's rings, gas giant planet, cosmic beauty, ring system, professional space photography, astronomical wonder, planetary magnificence, celestial jewel, stunning view",
        "Галактика Андромеды, спиральная структура": "Andromeda galaxy, spiral structure, neighboring galaxy, deep space photography, professional astrophotography, cosmic scale, stellar beauty, astronomical wonder, 8K detailed",
        "Астронавт в открытом космосе, невесомость": "Astronaut spacewalk, zero gravity, orbital EVA, Earth backdrop, professional space photography, space suit, cosmic adventure, human achievement, heroic moment",
        "Лунная поверхность, кратеры, Земля на горизонте": "Lunar surface, impact craters, Earth rising, moon landscape, professional space photography, Apollo legacy, grey terrain, cosmic perspective, historical achievement",
        "Комета, хвост, звездное небо": "Comet passing, glowing tail, starry background, celestial visitor, professional astrophotography, ice and dust, cosmic traveler, astronomical event, dramatic trajectory",
        "Солнечная вспышка, корона, энергия": "Solar flare, sun's corona, massive energy release, astronomical photography, professional space photography, stellar activity, plasma eruption, cosmic power, scientific observation",
        "Экзопланета, чужой мир, два солнца": "Exoplanet landscape, alien world, binary star system, two suns, professional sci-fi art, otherworldly environment, astronomical concept, imaginative scenery, cosmic wonder",
        "Космический корабль будущего, межзвездный полет": "Futuristic spaceship, interstellar travel, advanced propulsion, sci-fi vessel, professional concept art, space exploration, sleek design, cosmic journey, technological marvel",
        "Пульсар, нейтронная звезда, излучение": "Pulsar visualization, neutron star, electromagnetic radiation, astronomical phenomenon, professional scientific illustration, rotating beacon, cosmic lighthouse, extreme physics, stellar remnant",
        
        # Макросъемка
        "Капля воды, отражение, макро, детали": "Water droplet macro, reflection details, surface tension, professional macro photography, crystal clarity, natural beauty, detailed close-up, pristine liquid, 8K ultra sharp",
        "Глаз крупным планом, радужка, ресницы": "Eye extreme close-up, iris details, eyelashes, professional macro photography, human anatomy, colorful patterns, detailed texture, emotional window, stunning clarity",
        "Насекомое, детали, крылья, макросъемка": "Insect macro photography, wing details, compound eyes, professional nature shot, intricate anatomy, natural beauty, detailed close-up, scientific accuracy, stunning clarity",
        "Цветок, тычинки, пыльца, красота": "Flower macro, stamen details, pollen grains, professional botanical photography, natural beauty, vibrant colors, delicate structure, detailed close-up, soft natural light",
        "Снежинка, кристаллы, уникальность, макро": "Snowflake macro, ice crystals, unique pattern, professional winter photography, hexagonal symmetry, frozen beauty, detailed structure, natural geometry, pristine clarity",
        "Текстура кожи, поры, детали, реализм": "Skin texture macro, pore details, realistic surface, professional photography, human anatomy, natural imperfection, detailed close-up, authentic beauty, ultra sharp",
        "Перо птицы, структура, легкость, макро": "Bird feather macro, intricate structure, delicate barbs, professional nature photography, natural engineering, lightweight beauty, detailed close-up, soft texture, stunning clarity",
        "Паутина с росой, капли, утро, детали": "Spider web with dew, morning droplets, delicate structure, professional macro photography, natural geometry, water beads, intricate pattern, peaceful dawn, stunning details",
        "Кристалл, грани, свет, макросъемка": "Crystal macro, faceted surfaces, light refraction, professional photography, geometric beauty, transparent clarity, rainbow spectrum, natural formation, stunning details",
        "Ткань, волокна, текстура, крупный план": "Fabric macro, fiber details, textile texture, professional photography, woven pattern, material close-up, intricate structure, tactile quality, detailed surface",
        "Монета, детали, металл, макро": "Coin macro photography, engraved details, metallic surface, professional numismatic shot, historical artifact, intricate design, aged patina, cultural heritage, ultra sharp",
        "Лист растения, прожилки, структура": "Plant leaf macro, vein structure, natural patterns, professional botanical photography, chlorophyll green, organic geometry, detailed texture, biological beauty, scientific accuracy",
        "Песчинки, разнообразие, макро, пляж": "Sand grains macro, diverse particles, beach composition, professional photography, natural variety, colorful minerals, detailed close-up, geological beauty, stunning clarity",
        "Пузырьки, мыло, радуга, макросъемка": "Soap bubbles macro, rainbow iridescence, spherical forms, professional photography, surface tension, colorful reflections, delicate beauty, ephemeral art, stunning details",
        "Ржавчина, текстура, время, детали": "Rust texture macro, oxidation patterns, weathered metal, professional photography, natural decay, orange-brown tones, aged surface, time's passage, detailed corrosion",
        
        # Медитация
        "Йога на рассвете, медитация, гармония, природа": "Sunrise yoga, meditation practice, natural harmony, peaceful pose, professional photography, spiritual wellness, outdoor setting, golden hour light, mindful moment, zen atmosphere",
        "Дзен сад, камни, песок, спокойствие": "Zen rock garden, raked sand patterns, meditation stones, Japanese tradition, professional photography, peaceful atmosphere, minimalist beauty, spiritual practice, tranquil setting",
        "Медитация у воды, отражение, тишина": "Waterside meditation, peaceful reflection, silent contemplation, natural setting, professional photography, spiritual practice, calm waters, mindful moment, serene atmosphere",
        "Свечи и благовония, релакс, атмосфера": "Meditation candles, burning incense, relaxation atmosphere, spiritual practice, professional photography, aromatic ambiance, peaceful setting, mindful space, calming environment",
        "Лотос на воде, символ, чистота, покой": "Lotus flower, water surface, purity symbol, peaceful beauty, professional nature photography, spiritual significance, serene atmosphere, Buddhist symbolism, tranquil scene",
        "Тибетские поющие чаши, звук, медитация": "Tibetan singing bowls, sound meditation, vibrational healing, spiritual practice, professional photography, traditional instruments, peaceful atmosphere, mindful ritual, harmonic resonance",
        "Мандала, узор, концентрация, искусство": "Mandala pattern, meditative art, sacred geometry, concentration focus, professional photography, spiritual symbolism, intricate design, Buddhist tradition, artistic meditation",
        "Медитация в лесу, природа, единение": "Forest meditation, nature connection, woodland peace, spiritual practice, professional photography, natural sanctuary, mindful moment, environmental harmony, serene atmosphere",
        "Спокойное озеро, отражение, тишина": "Peaceful lake, mirror reflection, silent waters, natural tranquility, professional landscape photography, meditative scene, calm atmosphere, pristine nature, zen moment",
        "Бамбуковый лес, зелень, покой, Япония": "Bamboo forest, lush greenery, peaceful atmosphere, Japanese nature, professional photography, zen environment, natural sanctuary, meditative setting, serene beauty",
        "Закат над морем, медитация, созерцание": "Ocean sunset meditation, contemplative moment, peaceful seascape, spiritual practice, professional photography, natural beauty, mindful observation, tranquil atmosphere, golden hour",
        "Ароматерапия, эфирные масла, релакс": "Aromatherapy, essential oils, relaxation therapy, wellness practice, professional photography, natural healing, peaceful atmosphere, mindful self-care, calming scents",
        "Тихий храм, молитва, духовность": "Quiet temple, prayer meditation, spiritual sanctuary, sacred space, professional photography, religious atmosphere, peaceful worship, cultural heritage, divine presence",
        "Медитация на горе, высота, перспектива": "Mountain meditation, elevated perspective, spiritual practice, natural setting, professional photography, panoramic view, mindful moment, peaceful solitude, zen atmosphere",
        "Спокойное дыхание, осознанность, момент": "Mindful breathing, conscious awareness, present moment, meditation practice, professional photography, peaceful expression, spiritual wellness, calm state, inner peace",
        
        # Минимализм
        "Одинокое дерево в поле, минимализм, простота": "Solitary tree in field, minimalist landscape, simple composition, negative space, professional photography, clean aesthetic, peaceful scene, zen simplicity, natural beauty",
        "Геометрические формы, чистота, минимализм": "Geometric shapes, clean design, minimalist composition, precise forms, professional photography, modern aesthetic, balanced symmetry, simple elegance, contemporary art",
        "Белая комната, пустота, пространство": "White room, empty space, minimalist interior, clean aesthetic, professional photography, negative space, pure simplicity, modern design, zen atmosphere",
        "Один объект на столе, фокус, простота": "Single object on table, focused composition, simple presentation, minimalist still life, professional photography, clean background, isolated subject, zen aesthetic",
        "Линия горизонта, небо и земля, минимализм": "Horizon line, sky meets earth, minimalist landscape, simple division, professional photography, clean composition, natural beauty, zen simplicity, peaceful scene",
        "Тень на стене, графика, минимализм": "Shadow on wall, graphic composition, minimalist art, light and dark, professional photography, simple beauty, geometric pattern, clean aesthetic, contemporary style",
        "Капля на поверхности, простота, фокус": "Single droplet, surface tension, minimalist macro, focused detail, professional photography, simple beauty, clean composition, natural form, zen moment",
        "Монохромная композиция, оттенки, минимализм": "Monochromatic composition, tonal variations, minimalist aesthetic, grayscale beauty, professional photography, simple elegance, subtle gradients, clean design, contemporary art",
        "Пустая дорога, перспектива, простота": "Empty road, vanishing perspective, minimalist landscape, simple composition, professional photography, clean lines, peaceful journey, zen simplicity, open space",
        "Одинокая фигура, пространство, минимализм": "Solitary figure, vast space, minimalist composition, human scale, professional photography, negative space, simple beauty, contemplative mood, zen aesthetic",
        "Круг на фоне, геометрия, чистота": "Circle on background, geometric purity, minimalist design, simple form, professional photography, clean composition, balanced symmetry, modern aesthetic, zen simplicity",
        "Минималистичный пейзаж, небо, земля": "Minimalist landscape, sky and earth, simple horizon, clean composition, professional photography, natural beauty, peaceful scene, zen aesthetic, contemporary style",
        "Один цвет, градиент, простота": "Single color gradient, tonal transition, minimalist art, simple beauty, professional photography, clean aesthetic, smooth blend, contemporary design, zen simplicity",
        "Линии и формы, абстракция, минимализм": "Lines and shapes, abstract minimalism, geometric composition, clean design, professional photography, simple elegance, modern aesthetic, balanced forms, zen beauty",
        "Пустое пространство, воздух, свобода": "Empty space, negative area, minimalist freedom, clean composition, professional photography, breathing room, zen simplicity, peaceful void, contemporary aesthetic",
        
        # Мифология
        "Греческие боги на Олимпе, величие, мифы": "Greek gods on Mount Olympus, divine majesty, mythological scene, classical mythology, professional digital art, epic scale, ancient legends, powerful deities, dramatic atmosphere",
        "Скандинавские боги, Асгард, Один, Тор": "Norse gods, Asgard realm, Odin and Thor, Viking mythology, professional concept art, epic warriors, mythological power, dramatic scene, legendary figures",
        "Египетские боги, Анубис, Ра, древность": "Egyptian deities, Anubis and Ra, ancient mythology, pharaonic art, professional illustration, hieroglyphic style, divine power, cultural heritage, mystical atmosphere",
        "Единорог в волшебном лесу, магия, чистота": "Unicorn in enchanted forest, magical creature, pure white, mythical beast, professional fantasy art, mystical atmosphere, legendary animal, ethereal beauty, fairy tale scene",
        "Минотавр в лабиринте, греческая мифология": "Minotaur in labyrinth, Greek mythology, half-man half-bull, ancient legend, professional concept art, dark maze, mythical creature, dramatic atmosphere, classical tale",
        "Медуза Горгона, змеи вместо волос, взгляд": "Medusa Gorgon, snake hair, petrifying gaze, Greek mythology, professional fantasy art, monstrous beauty, mythical creature, dramatic portrait, legendary monster",
        "Кентавр, получеловек-полуконь, мудрость": "Centaur, half-human half-horse, wise creature, Greek mythology, professional fantasy art, mythical being, noble warrior, classical legend, majestic presence",
        "Сирены, море, пение, соблазн": "Sirens, ocean creatures, enchanting song, Greek mythology, professional fantasy art, seductive danger, mythical beings, maritime legend, beautiful monsters",
        "Грифон, лев с крыльями орла, страж": "Griffin, lion-eagle hybrid, guardian creature, mythological beast, professional fantasy art, powerful protector, legendary animal, majestic presence, ancient symbol",
        "Цербер, трехглавый пес, подземный мир": "Cerberus, three-headed dog, underworld guardian, Greek mythology, professional fantasy art, fearsome beast, mythical creature, dark atmosphere, legendary monster",
        "Пегас, крылатый конь, полет, свобода": "Pegasus, winged horse, soaring flight, Greek mythology, professional fantasy art, majestic creature, mythical steed, freedom symbol, legendary beauty",
        "Химера, огнедышащее чудовище, миф": "Chimera, fire-breathing monster, hybrid creature, Greek mythology, professional fantasy art, fearsome beast, mythical horror, dramatic scene, legendary terror",
        "Валькирии, воительницы, скандинавская мифология": "Valkyries, warrior maidens, Norse mythology, battlefield choosers, professional fantasy art, winged warriors, legendary figures, dramatic scene, Viking legends",
        "Сфинкс, загадка, древний Египет": "Sphinx, riddle keeper, ancient Egypt, mythical guardian, professional concept art, mysterious creature, cultural icon, desert monument, legendary wisdom",
        "Гидра, многоголовый змей, битва": "Hydra, multi-headed serpent, epic battle, Greek mythology, professional fantasy art, regenerating monster, legendary creature, heroic combat, mythical challenge",
        
        # Мода (продолжение)
        "Высокая мода, подиум, дизайнерское платье": "High fashion runway, designer gown, catwalk presentation, professional fashion photography, luxury couture, elegant model, dramatic lighting, Vogue quality, sophisticated style",
        "Уличная мода, стритстайл, современный образ": "Street style fashion, urban outfit, contemporary look, candid photography, city backdrop, professional fashion shot, trendy aesthetic, modern lifestyle, editorial quality",
        "Винтажная мода, ретро стиль, 50-е годы": "Vintage 1950s fashion, retro styling, classic elegance, period costume, professional fashion photography, nostalgic aesthetic, timeless beauty, authentic details, pin-up style",
        "Авангардная мода, необычный крой, искусство": "Avant-garde fashion, experimental design, artistic clothing, unconventional cut, professional editorial photography, bold statement, creative expression, fashion art, innovative concept",
        "Деловой стиль, костюм, элегантность": "Business fashion, tailored suit, professional elegance, corporate style, editorial photography, confident pose, executive look, modern professional, polished appearance",
        "Бохо стиль, свободный крой, этнические мотивы": "Boho fashion, flowing silhouettes, ethnic patterns, free-spirited style, professional photography, natural fabrics, bohemian aesthetic, relaxed elegance, earthy tones",
        "Спортивная мода, athleisure, комфорт": "Athleisure fashion, athletic wear, comfortable style, active lifestyle, professional photography, modern sportswear, functional design, fitness aesthetic, contemporary trend",
        "Вечернее платье, роскошь, блеск": "Evening gown, luxury fashion, glamorous sparkle, formal elegance, professional photography, red carpet style, sophisticated design, high-end couture, dramatic presentation",
        "Минималистичный стиль, черно-белая гамма": "Minimalist fashion, black and white palette, clean lines, simple elegance, professional photography, contemporary style, understated chic, modern aesthetic, refined look",
        "Панк мода, кожа, заклепки, бунтарство": "Punk fashion, leather clothing, metal studs, rebellious style, professional photography, alternative aesthetic, edgy look, youth culture, bold statement",
        "Романтический стиль, кружева, нежность": "Romantic fashion, lace details, delicate femininity, soft fabrics, professional photography, gentle elegance, vintage inspiration, dreamy aesthetic, tender beauty",
        "Футуристическая мода, металлик, инновации": "Futuristic fashion, metallic fabrics, innovative design, sci-fi aesthetic, professional photography, avant-garde style, technological inspiration, bold concept, modern innovation",
        "Этническая мода, национальные костюмы": "Ethnic fashion, traditional costumes, cultural clothing, national dress, professional photography, heritage style, authentic details, cultural pride, colorful patterns",
        "Гранж стиль, небрежность, многослойность": "Grunge fashion, casual layering, effortless style, 90s aesthetic, professional photography, relaxed vibe, alternative look, urban edge, contemporary trend",
        "Гламурный стиль, блестки, яркость": "Glamorous fashion, sequin sparkle, dazzling style, luxury aesthetic, professional photography, red carpet look, bold statement, high-end fashion, dramatic presentation",
        
        # Музыка (продолжение)
        "Концерт, сцена, музыканты, свет, энергия": "Live concert, stage performance, musicians playing, dynamic lighting, professional music photography, energetic atmosphere, crowd excitement, rock show, 8K detailed, festival energy",
        "Пианино, клавиши, классическая музыка": "Grand piano, ivory keys, classical performance, elegant instrument, professional music photography, concert hall, musical artistry, refined atmosphere, acoustic perfection",
        "Гитара, струны, рок-музыка, страсть": "Electric guitar, vibrating strings, rock performance, passionate playing, professional music photography, stage presence, musical intensity, concert energy, dramatic lighting",
        "Скрипка, смычок, оркестр, элегантность": "Violin performance, bow technique, orchestra setting, elegant instrument, professional music photography, classical beauty, musical precision, refined artistry, concert atmosphere",
        "Барабаны, ритм, энергия, удар": "Drum kit, rhythmic power, energetic performance, percussion impact, professional music photography, dynamic motion, musical intensity, concert lighting, powerful beats",
        "Саксофон, джаз, импровизация, душа": "Saxophone jazz, improvisational soul, brass instrument, intimate performance, professional music photography, moody lighting, musical expression, club atmosphere, soulful artistry",
        "Диджей за пультом, электронная музыка, клуб": "DJ mixing, electronic music, club atmosphere, turntables and mixer, professional photography, nightlife energy, neon lights, party vibes, dynamic composition",
        "Хор, пение, гармония, голоса": "Choir singing, vocal harmony, group performance, unified voices, professional music photography, concert hall, musical unity, cultural event, acoustic excellence",
        "Флейта, духовой инструмент, мелодия": "Flute performance, wind instrument, melodic beauty, classical music, professional photography, elegant playing, musical artistry, refined atmosphere, acoustic purity",
        "Виолончель, классика, глубокий звук": "Cello performance, deep resonance, classical instrument, rich tones, professional music photography, concert setting, musical depth, refined artistry, acoustic beauty",
        "Синтезатор, электронная музыка, технологии": "Synthesizer, electronic music, modern technology, keyboard instrument, professional photography, digital sound, creative workspace, innovative music, contemporary production",
        "Арфа, струны, небесная музыка": "Harp performance, heavenly strings, angelic music, classical instrument, professional photography, elegant playing, ethereal sound, refined beauty, acoustic perfection",
        "Труба, духовой оркестр, мощный звук": "Trumpet performance, brass power, orchestral might, wind instrument, professional music photography, bold sound, musical intensity, concert atmosphere, dynamic presence",
        "Укулеле, гавайская музыка, легкость": "Ukulele playing, Hawaiian music, light melodies, tropical instrument, professional photography, island vibes, cheerful sound, casual performance, relaxed atmosphere",
        "Контрабас, джаз, низкие ноты": "Double bass, jazz performance, deep notes, large instrument, professional music photography, rhythmic foundation, musical depth, club atmosphere, soulful playing",
        
        # Наука (продолжение)
        "Лаборатория, микроскоп, исследование, наука": "Scientific laboratory, microscope research, experimental work, modern equipment, professional photography, scientific discovery, clean environment, technical precision, 8K detailed",
        "ДНК спираль, генетика, молекулярная биология": "DNA double helix, genetic code, molecular biology, scientific visualization, professional illustration, biotechnology research, medical science, detailed structure, 3D rendering",
        "Химическая реакция, колбы, эксперимент": "Chemical reaction, laboratory glassware, scientific experiment, colorful solutions, professional photography, bubbling liquids, research environment, educational science, precise measurement",
        "Телескоп, астрономия, звезды, наблюдение": "Astronomical telescope, stargazing, celestial observation, scientific instrument, professional photography, night sky research, observatory setting, cosmic exploration, technical precision",
        "Анатомия человека, медицина, изучение": "Human anatomy, medical study, anatomical model, healthcare education, professional photography, scientific accuracy, biological structure, medical training, detailed illustration",
        "Физический эксперимент, энергия, открытие": "Physics experiment, energy demonstration, scientific discovery, laboratory setup, professional photography, theoretical proof, research breakthrough, educational science, innovative concept",
        "Археологические раскопки, древности, история": "Archaeological dig, ancient artifacts, historical excavation, scientific research, professional photography, cultural heritage, careful documentation, discovery moment, preservation work",
        "Ботаника, растения, исследование, природа": "Botanical research, plant specimens, scientific study, natural science, professional photography, biological diversity, detailed observation, educational documentation, environmental study",
        "Математические формулы, доска, расчеты": "Mathematical equations, blackboard formulas, complex calculations, scientific notation, professional photography, theoretical work, academic environment, intellectual pursuit, problem solving",
        "Геология, минералы, кристаллы, изучение": "Geological specimens, mineral crystals, rock formations, earth science, professional photography, natural beauty, scientific study, colorful minerals, crystalline structure",
        "Океанография, подводные исследования": "Oceanographic research, underwater exploration, marine science, deep sea study, professional photography, ocean discovery, scientific equipment, environmental research, aquatic investigation",
        "Метеорология, погода, прогноз, наблюдение": "Meteorology, weather patterns, forecast science, atmospheric study, professional photography, climate observation, scientific instruments, environmental monitoring, weather prediction",
        "Палеонтология, динозавры, окаменелости": "Paleontology, dinosaur fossils, ancient remains, prehistoric study, professional photography, scientific excavation, evolutionary history, geological time, fossil documentation",
        "Нейронаука, мозг, исследование сознания": "Neuroscience research, brain study, consciousness exploration, neural imaging, professional photography, cognitive science, medical technology, mental processes, scientific breakthrough",
        "Экология, природа, сохранение, баланс": "Ecological research, nature conservation, environmental balance, biodiversity study, professional photography, sustainability science, ecosystem protection, natural harmony, scientific observation",
        
        # Ночь
        "Ночной город, огни, небоскребы, жизнь": "Night city, glowing lights, skyscrapers illuminated, urban nightlife, professional cityscape photography, vibrant energy, metropolitan atmosphere, 8K ultra detailed, dramatic skyline",
        "Звездное небо, млечный путь, космос": "Starry night sky, Milky Way galaxy, cosmic view, professional astrophotography, celestial beauty, dark sky location, astronomical wonder, long exposure, infinite universe",
        "Луна над морем, отражение, романтика": "Moon over ocean, water reflection, romantic atmosphere, night seascape, professional photography, peaceful scene, lunar beauty, tranquil waters, dreamy mood",
        "Ночной лес, тайна, тишина, природа": "Night forest, mysterious atmosphere, silent woods, natural darkness, professional photography, moonlit trees, peaceful solitude, nocturnal beauty, atmospheric scene",
        "Костер в ночи, огонь, тепло, уют": "Campfire at night, crackling flames, warm glow, cozy gathering, professional photography, outdoor comfort, peaceful atmosphere, natural light, camping scene",
        "Ночная улица, фонари, тени, атмосфера": "Night street, street lamps, dramatic shadows, urban atmosphere, professional photography, moody lighting, city scene, nocturnal beauty, cinematic mood",
        "Северное сияние, ночь, магия, небо": "Aurora borealis, night sky, magical lights, Arctic phenomenon, professional astrophotography, vibrant colors, natural wonder, celestial display, breathtaking beauty",
        "Ночной пляж, волны, луна, спокойствие": "Night beach, ocean waves, moonlight, peaceful seascape, professional photography, tranquil atmosphere, coastal beauty, serene waters, romantic scene",
        "Окно с светом в ночи, уют, дом": "Lit window at night, cozy home, warm interior, nighttime exterior, professional photography, inviting glow, domestic comfort, peaceful scene, atmospheric beauty",
        "Ночной дождь, отражения, огни города": "Night rain, wet reflections, city lights, urban atmosphere, professional photography, moody scene, glistening pavement, dramatic weather, cinematic mood",
        "Кемпинг под звездами, палатка, природа": "Camping under stars, tent setup, natural setting, night sky, professional photography, outdoor adventure, peaceful wilderness, starry backdrop, camping lifestyle",
        "Ночной порт, корабли, огни, вода": "Night harbor, ships docked, port lights, water reflections, professional photography, maritime atmosphere, industrial beauty, peaceful scene, nautical mood",
        "Ночная дорога, фары, путь, движение": "Night highway, car headlights, road ahead, motion blur, professional photography, journey atmosphere, urban travel, dynamic scene, cinematic composition",
        "Ночной парк, фонари, тени, прогулка": "Night park, lamp posts, tree shadows, evening stroll, professional photography, peaceful atmosphere, urban nature, romantic setting, quiet beauty",
        "Ночное кафе, свет, уют, атмосфера": "Night café, warm lighting, cozy atmosphere, urban setting, professional photography, inviting interior, social space, peaceful evening, intimate ambiance",
        
        # Пейзаж (продолжение)
        "Горный пейзаж на рассвете, туман в долине, золотой час": "Mountain landscape at dawn, valley fog, golden hour lighting, alpine scenery, professional landscape photography, dramatic peaks, atmospheric beauty, 8K ultra detailed, breathtaking vista",
        "Морской берег на закате, волны, розовое небо": "Seashore at sunset, rolling waves, pink sky, coastal beauty, professional landscape photography, peaceful atmosphere, golden hour, tranquil waters, romantic scene",
        "Лесная тропа осенью, золотые листья, солнечные лучи": "Forest trail in autumn, golden leaves, sun rays filtering, fall foliage, professional landscape photography, natural path, seasonal beauty, warm colors, peaceful walk",
        "Зимний пейзаж, заснеженные деревья, голубое небо": "Winter landscape, snow-covered trees, blue sky, frozen beauty, professional landscape photography, pristine white, cold season, peaceful scene, crisp atmosphere",
        "Поле лаванды в Провансе, фиолетовые цветы, летний день": "Lavender field Provence, purple flowers, summer day, French countryside, professional landscape photography, aromatic beauty, pastoral scene, vibrant colors, peaceful atmosphere",
        "Городской пейзаж ночью, небоскребы, огни города": "Urban night landscape, skyscrapers, city lights, metropolitan skyline, professional cityscape photography, vibrant energy, modern architecture, 8K detailed, dramatic atmosphere",
        "Водопад в тропическом лесу, зелень, радуга в брызгах": "Tropical waterfall, lush rainforest, rainbow in mist, cascading water, professional landscape photography, natural wonder, vibrant green, pristine beauty, long exposure",
        "Пустынный пейзаж, дюны, звездное небо": "Desert landscape, sand dunes, starry night, arid beauty, professional landscape photography, Milky Way visible, vast wilderness, peaceful solitude, dramatic contrast",
        "Альпийский луг, горные цветы, снежные вершины вдали": "Alpine meadow, wildflowers, distant snow peaks, mountain scenery, professional landscape photography, natural beauty, seasonal bloom, pristine environment, peaceful setting",
        "Озеро в горах, отражение, спокойная вода": "Mountain lake, mirror reflection, calm waters, alpine scenery, professional landscape photography, peaceful atmosphere, pristine nature, dramatic backdrop, serene beauty",
        "Сельский пейзаж, поля пшеницы, старая мельница": "Rural landscape, wheat fields, old windmill, countryside beauty, professional landscape photography, agricultural scene, pastoral charm, golden crops, peaceful setting",
        "Каньон на закате, красные скалы, драматическое небо": "Canyon at sunset, red rock formations, dramatic sky, geological wonder, professional landscape photography, epic scenery, natural erosion, vibrant colors, vast scale",
        "Тропический пляж, белый песок, бирюзовая вода": "Tropical beach, white sand, turquoise water, paradise setting, professional landscape photography, coastal beauty, crystal clear, peaceful atmosphere, vacation dream",
        "Северное сияние над заснеженным лесом": "Aurora borealis over snowy forest, northern lights, winter landscape, magical phenomenon, professional astrophotography, vibrant colors, Arctic beauty, natural wonder, breathtaking scene",
        "Виноградники на холмах, закат, Тоскана": "Vineyard hills, Tuscan sunset, rolling landscape, wine country, professional landscape photography, Italian countryside, golden hour, agricultural beauty, peaceful scene",
        
        # Подводный мир
        "Коралловый риф, разноцветные рыбы, красота": "Coral reef ecosystem, colorful tropical fish, underwater beauty, marine biodiversity, professional underwater photography, vibrant life, ocean wonder, crystal clear water, natural paradise",
        "Акула в океане, хищник, мощь": "Shark in ocean, apex predator, powerful presence, marine wildlife, professional underwater photography, natural behavior, ocean depths, majestic creature, dramatic encounter",
        "Медузы, свечение, грация, глубина": "Jellyfish, bioluminescent glow, graceful movement, deep ocean, professional underwater photography, ethereal beauty, floating creatures, natural wonder, mesmerizing dance",
        "Кит под водой, величие, океан": "Whale underwater, majestic giant, ocean depths, marine mammal, professional underwater photography, powerful grace, natural behavior, enormous scale, peaceful presence",
        "Осьминог, щупальца, интеллект, камуфляж": "Octopus, tentacles extended, intelligent creature, camouflage ability, professional underwater photography, marine biology, color changing, natural wonder, detailed texture",
        "Морской конек, необычная форма, нежность": "Seahorse, unique shape, delicate creature, marine oddity, professional underwater photography, gentle beauty, coral habitat, natural wonder, intricate details",
        "Скат манта, полет под водой, элегантность": "Manta ray, underwater flight, elegant gliding, marine giant, professional underwater photography, graceful movement, ocean beauty, majestic creature, peaceful presence",
        "Стая рыб, синхронность, движение": "Fish school, synchronized swimming, coordinated movement, marine behavior, professional underwater photography, natural pattern, ocean life, dynamic motion, collective beauty",
        "Морская звезда, дно океана, спокойствие": "Starfish, ocean floor, peaceful creature, marine invertebrate, professional underwater photography, natural beauty, calm waters, detailed texture, serene atmosphere",
        "Краб, панцирь, клешни, дно": "Crab, hard shell, powerful claws, ocean bottom, professional underwater photography, marine crustacean, natural armor, detailed close-up, coastal creature",
        "Анемоны и рыба-клоун, симбиоз, яркость": "Sea anemones and clownfish, symbiotic relationship, vibrant colors, marine partnership, professional underwater photography, coral reef, natural cooperation, tropical beauty, Finding Nemo",
        "Затонувший корабль, тайна, история": "Sunken shipwreck, underwater mystery, historical vessel, marine archaeology, professional underwater photography, artificial reef, ocean history, eerie beauty, time capsule",
        "Пещера под водой, свет, исследование": "Underwater cave, light penetration, diving exploration, submerged cavern, professional underwater photography, natural formation, mysterious depths, adventure diving, geological wonder",
        "Планктон, свечение, микромир": "Bioluminescent plankton, glowing microorganisms, microscopic world, marine biology, professional photography, natural light show, ocean magic, tiny creatures, ethereal beauty",
        "Морской лев, игривость, грация": "Sea lion, playful behavior, graceful swimming, marine mammal, professional underwater photography, natural joy, ocean acrobat, charming creature, dynamic movement",
        
        # Портрет (продолжение)
        "Деловой портрет в костюме, офисный фон, профессиональная съемка": "Corporate business portrait, professional suit, office background, executive presence, professional photography, confident expression, modern setting, polished appearance, LinkedIn quality",
        "Художественный портрет в стиле ренессанс, классическое освещение": "Renaissance-style portrait, classical lighting, fine art photography, historical aesthetic, dramatic chiaroscuro, timeless elegance, museum quality, sophisticated composition, artistic mastery",
        "Портрет в золотой час, теплый свет заката, романтическая атмосфера": "Golden hour portrait, sunset warmth, romantic atmosphere, natural light, professional photography, soft shadows, dreamy mood, environmental portrait, beautiful bokeh",
        "Черно-белый портрет, драматическое освещение, высокий контраст": "Black and white portrait, dramatic lighting, high contrast, monochrome photography, professional studio work, emotional depth, timeless aesthetic, artistic expression, gallery quality",
        "Портрет модели, модный макияж, студийная съемка": "Fashion model portrait, editorial makeup, studio photography, professional lighting, glamorous look, high-end retouching, Vogue aesthetic, beauty photography, sophisticated style",
        "Портрет спортсмена, энергичный взгляд, динамичная поза": "Athlete portrait, energetic expression, dynamic pose, professional sports photography, powerful presence, determined look, fitness aesthetic, motivational image, strength showcase",
        "Портрет художника за работой, творческая атмосфера": "Artist portrait, creative workspace, painting in progress, professional photography, artistic environment, passionate expression, cultural documentation, studio atmosphere, authentic moment",
        "Семейный портрет, теплая атмосфера, естественные эмоции": "Family portrait, warm atmosphere, natural emotions, group photography, professional shot, genuine interaction, loving connection, lifestyle photography, generational bond",
        "Портрет музыканта с инструментом, артистическое освещение": "Musician portrait, instrument featured, artistic lighting, professional photography, creative composition, cultural documentation, passionate performer, storytelling image, authentic expression",
        "Портрет в национальном костюме, культурные детали": "Traditional costume portrait, cultural attire, ethnic clothing, heritage photography, professional shot, authentic details, national pride, cultural preservation, colorful garments",
        "Портрет танцора в движении, грация и элегантность": "Dancer portrait, graceful movement, elegant pose, professional dance photography, artistic expression, dynamic composition, flowing lines, performance art, beautiful form",
        "Портрет ученого в лаборатории, интеллектуальный образ": "Scientist portrait, laboratory setting, intellectual presence, professional photography, research environment, thoughtful expression, academic atmosphere, scientific dedication, knowledgeable look",
        
        # Праздники
        "Новогодняя елка, гирлянды, подарки, уют": "Christmas tree, string lights, wrapped presents, cozy atmosphere, professional holiday photography, festive decorations, warm glow, family tradition, seasonal joy",
        "День рождения, торт со свечами, праздник": "Birthday celebration, cake with candles, festive party, joyful moment, professional photography, colorful decorations, happy gathering, special occasion, celebratory atmosphere",
        "Свадебная церемония, невеста, цветы, счастье": "Wedding ceremony, bride portrait, floral arrangements, joyful celebration, professional wedding photography, romantic atmosphere, special day, elegant details, love story",
        "Хэллоуин, тыквы, мистика, осень": "Halloween celebration, carved pumpkins, mystical atmosphere, autumn holiday, professional photography, spooky decorations, orange glow, festive tradition, seasonal fun",
        "Рождество, камин, носки, семья": "Christmas fireplace, stockings hung, family gathering, holiday tradition, professional photography, cozy atmosphere, festive decorations, warm glow, seasonal joy",
        "Пасха, крашеные яйца, весна, традиции": "Easter celebration, decorated eggs, spring holiday, traditional customs, professional photography, colorful display, seasonal festivity, family tradition, joyful atmosphere",
        "День святого Валентина, сердца, романтика": "Valentine's Day, heart decorations, romantic celebration, love holiday, professional photography, red and pink, intimate atmosphere, special occasion, tender moments",
        "Фейерверк, ночное небо, праздник, огни": "Fireworks display, night sky, celebration lights, explosive colors, professional photography, festive atmosphere, dramatic bursts, special occasion, spectacular show",
        "Карнавал, маски, костюмы, веселье": "Carnival celebration, decorative masks, elaborate costumes, festive fun, professional photography, cultural tradition, vibrant colors, joyful atmosphere, street party",
        "Выпускной, студенты, радость, достижение": "Graduation ceremony, students celebrating, joyful achievement, academic milestone, professional photography, cap and gown, proud moment, educational success, future beginning",
        "Детский праздник, шары, торт, смех": "Children's party, colorful balloons, birthday cake, joyful laughter, professional photography, festive decorations, happy kids, celebration atmosphere, fun activities",
        "Юбилей, торжество, элегантность": "Anniversary celebration, elegant gathering, formal event, milestone occasion, professional photography, sophisticated atmosphere, special moment, refined decorations, joyful celebration",
        "Фестиваль, музыка, толпа, энергия": "Music festival, massive crowd, energetic atmosphere, outdoor concert, professional event photography, summer vibes, cultural gathering, live performance, vibrant scene",
        "Пикник, природа, еда, отдых": "Outdoor picnic, nature setting, food spread, relaxation time, professional lifestyle photography, summer activity, peaceful atmosphere, family gathering, casual dining",
        "Корпоратив, офис, украшения, команда": "Corporate party, office celebration, festive decorations, team gathering, professional event photography, workplace culture, holiday spirit, colleague bonding, festive atmosphere",
        
        # Приключения
        "Путешественник на вершине горы, достижение": "Traveler on mountain summit, achievement moment, peak conquest, professional adventure photography, triumphant pose, panoramic view, outdoor accomplishment, inspiring scene, epic landscape",
        "Исследователь в джунглях, приключение, природа": "Explorer in jungle, adventure quest, dense rainforest, professional photography, tropical expedition, natural discovery, wilderness journey, brave adventurer, exotic environment",
        "Карта сокровищ, поиск, тайна, приключение": "Treasure map, quest for riches, mysterious clues, adventure theme, professional photography, aged parchment, X marks spot, pirate legend, exciting journey",
        "Рюкзак и компас, путешествие, подготовка": "Backpack and compass, travel preparation, adventure gear, outdoor equipment, professional photography, journey essentials, exploration tools, wanderlust spirit, ready to explore",
        "Каноэ на реке, сплав, природа, адреналин": "Canoe on river, whitewater rafting, nature adventure, adrenaline rush, professional action photography, outdoor sport, water journey, exciting rapids, wilderness exploration",
        "Палатка в горах, кемпинг, звезды, свобода": "Mountain camping, tent setup, starry night, freedom feeling, professional photography, outdoor adventure, wilderness living, peaceful solitude, nature connection",
        "Дайвинг, подводный мир, исследование": "Scuba diving, underwater exploration, ocean discovery, marine adventure, professional underwater photography, diving equipment, coral reef, aquatic journey, natural wonder",
        "Парашютист в небе, прыжок, экстрим": "Skydiver in air, extreme jump, freefall moment, professional action photography, adrenaline sport, aerial perspective, thrilling experience, cloud backdrop, fearless adventure",
        "Сафари, дикие животные, Африка, приключение": "Safari adventure, wild animals, African landscape, nature expedition, professional wildlife photography, jeep tour, natural habitat, exciting encounter, cultural experience",
        "Альпинист на скале, восхождение, вызов": "Rock climber, cliff ascent, challenging route, professional action photography, vertical adventure, athletic skill, mountain face, determined effort, extreme sport",
        "Путешествие на мотоцикле, дорога, свобода": "Motorcycle journey, open road, freedom ride, adventure travel, professional photography, scenic route, wind in face, solo adventure, wanderlust spirit",
        "Исследование пещеры, фонарь, тайна": "Cave exploration, headlamp light, underground mystery, spelunking adventure, professional photography, geological wonder, dark depths, exciting discovery, natural formation",
        "Рафтинг, бурная река, команда, адреналин": "Whitewater rafting, turbulent river, team adventure, adrenaline rush, professional action photography, water sport, exciting rapids, group challenge, outdoor thrill",
        "Путешествие автостопом, дорога, встречи": "Hitchhiking journey, open road, chance encounters, adventure travel, professional photography, budget exploration, cultural exchange, freedom lifestyle, spontaneous adventure",
        "Экспедиция в Антарктиду, лед, исследование": "Antarctic expedition, ice exploration, polar adventure, scientific journey, professional photography, frozen wilderness, extreme environment, research mission, pristine beauty",
        
        # Природа (продолжение)
        "Роса на листьях, макросъемка, утренний свет": "Morning dew on leaves, macro photography, dawn light, water droplets, professional nature shot, fresh beginning, natural beauty, delicate details, peaceful atmosphere",
        "Гроза над полем, молнии, драматическое небо": "Thunderstorm over field, lightning strikes, dramatic sky, weather phenomenon, professional photography, natural power, atmospheric intensity, stormy beauty, electric display",
        "Радуга после дождя, яркие цвета, пейзаж": "Rainbow after rain, vibrant arc, landscape beauty, natural phenomenon, professional photography, colorful spectrum, hopeful symbol, weather beauty, atmospheric optics",
        "Цветущая сакура, розовые лепестки, весна": "Cherry blossoms, pink petals, spring bloom, Japanese sakura, professional nature photography, seasonal beauty, delicate flowers, cultural symbol, romantic atmosphere",
        "Грибы в лесу, мох, сказочная атмосфера": "Forest mushrooms, moss covered, fairy tale atmosphere, woodland scene, professional nature photography, natural growth, magical setting, earthy tones, enchanted forest",
        "Ледяные кристаллы, макро, зимние узоры": "Ice crystals macro, winter patterns, frost formations, frozen beauty, professional photography, delicate structure, natural geometry, cold season, pristine details",
        "Вулканическое извержение, лава, мощь природы": "Volcanic eruption, flowing lava, nature's power, geological event, professional photography, molten rock, dramatic scene, natural force, intense heat, spectacular display",
        "Коралловый риф, подводный мир, разнообразие": "Coral reef, underwater ecosystem, marine biodiversity, tropical ocean, professional underwater photography, vibrant life, natural wonder, colorful habitat, pristine environment",
        "Горный ручей, камни, чистая вода": "Mountain stream, rocky bed, crystal clear water, natural flow, professional landscape photography, pristine nature, peaceful sound, fresh water, scenic beauty",
        "Поле подсолнухов, желтые цветы, лето": "Sunflower field, yellow blooms, summer landscape, agricultural beauty, professional photography, vibrant colors, pastoral scene, natural abundance, cheerful atmosphere",
        "Туман в долине, мистическая атмосфера, утро": "Valley fog, mystical atmosphere, morning mist, ethereal landscape, professional photography, atmospheric beauty, peaceful scene, natural phenomenon, dreamy mood",
        "Звездное небо, млечный путь, ночь": "Starry night sky, Milky Way visible, celestial view, professional astrophotography, cosmic beauty, dark sky location, astronomical wonder, long exposure, infinite universe",
        "Ледник, голубой лед, арктический пейзаж": "Glacier landscape, blue ice formations, Arctic environment, frozen wilderness, professional nature photography, climate documentation, pristine beauty, dramatic scenery, natural wonder",
        "Тропический дождь, капли, зелень": "Tropical rainfall, rain droplets, lush greenery, jungle atmosphere, professional nature photography, wet season, vibrant vegetation, natural shower, fresh environment",
        "Осенние листья, разноцветье, текстуры": "Autumn leaves, colorful variety, natural textures, fall foliage, professional nature photography, seasonal transformation, warm tones, detailed close-up, natural beauty",
        
        # Профессии
        "Врач в операционной, концентрация, спасение": "Surgeon in operating room, focused concentration, life-saving work, medical professional, professional photography, sterile environment, critical care, healthcare hero, intense moment",
        "Учитель у доски, знания, образование": "Teacher at blackboard, knowledge sharing, educational setting, classroom instruction, professional photography, academic environment, inspiring educator, student learning, cultural importance",
        "Повар на кухне, кулинария, мастерство": "Chef in kitchen, culinary artistry, cooking mastery, professional photography, restaurant environment, food preparation, skilled technique, gastronomic excellence, creative cooking",
        "Пожарный, героизм, спасение, огонь": "Firefighter, heroic rescue, battling flames, emergency response, professional photography, protective gear, brave service, life-saving work, community hero",
        "Программист за компьютером, код, технологии": "Programmer coding, computer work, technology professional, software development, professional photography, modern workspace, digital creation, technical skill, innovative work",
        "Фотограф с камерой, искусство, момент": "Photographer with camera, artistic vision, capturing moment, professional photography, creative work, technical skill, visual storytelling, cultural documentation, passionate artist",
        "Строитель, стройка, труд, созидание": "Construction worker, building site, hard labor, creating structures, professional photography, physical work, skilled trade, urban development, honest work",
        "Пилот в кабине, небо, ответственность": "Pilot in cockpit, flight controls, aviation professional, sky responsibility, professional photography, technical expertise, safe travel, concentrated focus, skilled operator",
        "Ветеринар с животным, забота, лечение": "Veterinarian with animal, caring treatment, medical care, professional photography, compassionate work, pet health, healing touch, animal welfare, dedicated service",
        "Дизайнер за работой, творчество, идеи": "Designer working, creative process, innovative ideas, professional photography, artistic workspace, digital tools, visual creation, imaginative work, modern profession",
        "Механик, инструменты, ремонт, мастерство": "Mechanic working, repair tools, technical skill, professional photography, automotive service, hands-on work, problem solving, skilled trade, precision work",
        "Журналист, интервью, новости, правда": "Journalist interviewing, news gathering, truth seeking, professional photography, media work, investigative reporting, cultural documentation, information sharing, public service",
        "Фермер в поле, земля, урожай, труд": "Farmer in field, agricultural work, harvest time, professional photography, rural life, honest labor, food production, connection to land, traditional work",
        "Архитектор, чертежи, проектирование": "Architect designing, blueprints, creative planning, professional photography, technical drawings, innovative vision, building design, spatial thinking, modern profession",
        "Музыкант, инструмент, искусство, страсть": "Musician performing, instrument mastery, artistic passion, professional photography, musical expression, cultural work, creative dedication, emotional performance, skilled artistry",
        
        # Романтика
        "Пара на закате, любовь, романтика, силуэт": "Couple at sunset, romantic silhouette, love scene, golden hour, professional photography, intimate moment, peaceful atmosphere, relationship beauty, dreamy mood",
        "Свидание при свечах, ужин, интимность": "Candlelit dinner, romantic date, intimate setting, elegant dining, professional photography, warm ambiance, couple together, special evening, loving atmosphere",
        "Букет роз, цветы, любовь, подарок": "Rose bouquet, romantic flowers, love gift, red roses, professional photography, elegant arrangement, passionate symbol, special gesture, beautiful presentation",
        "Поцелуй под дождем, страсть, романтика": "Kiss in rain, passionate embrace, romantic moment, dramatic weather, professional photography, emotional intensity, cinematic scene, love story, atmospheric beauty",
        "Прогулка вдвоем, парк, осень, любовь": "Couple walking, autumn park, romantic stroll, fall foliage, professional photography, hand in hand, peaceful moment, relationship beauty, seasonal atmosphere",
        "Объятия на пляже, море, закат, нежность": "Beach embrace, ocean sunset, tender moment, romantic scene, professional photography, coastal beauty, loving couple, peaceful atmosphere, golden hour",
        "Романтический пикник, природа, вдвоем": "Romantic picnic, outdoor setting, couple together, nature backdrop, professional photography, intimate meal, peaceful atmosphere, love scene, beautiful day",
        "Танец пары, близость, гармония": "Couple dancing, intimate closeness, harmonious movement, romantic scene, professional photography, elegant pose, emotional connection, graceful motion, loving atmosphere",
        "Влюбленные под звездами, ночь, романтика": "Lovers under stars, night sky, romantic atmosphere, celestial backdrop, professional photography, peaceful moment, cosmic beauty, intimate scene, dreamy mood",
        "Сердце из лепестков, любовь, символ": "Heart made of petals, love symbol, romantic gesture, flower arrangement, professional photography, creative expression, tender message, beautiful display, emotional symbol",
        "Пара в кафе, разговор, уют": "Couple in café, intimate conversation, cozy setting, coffee date, professional photography, warm atmosphere, relationship moment, urban romance, comfortable space",
        "Романтическое письмо, чувства, слова": "Love letter, heartfelt words, romantic message, handwritten feelings, professional photography, emotional expression, tender communication, vintage charm, intimate gesture",
        "Пара на мосту, город, вечер": "Couple on bridge, city evening, romantic setting, urban landscape, professional photography, peaceful moment, relationship beauty, atmospheric lighting, love scene",
        "Обручальные кольца, свадьба, любовь": "Wedding rings, marriage symbol, eternal love, precious jewelry, professional photography, elegant presentation, commitment symbol, beautiful details, romantic tradition",
        "Романтический вечер, свечи, атмосфера": "Romantic evening, candlelight, intimate atmosphere, special occasion, professional photography, warm glow, peaceful setting, loving mood, tender moments",
    }
    
    # Обновляем промпты
    updated_count = 0
    for prompt in CategoryPrompt.objects.all():
        if prompt.prompt_text in prompts_mapping and not prompt.prompt_en:
            prompt.prompt_en = prompts_mapping[prompt.prompt_text]
            prompt.save(update_fields=['prompt_en'])
            updated_count += 1
    
    print(f"Часть 2: Обновлено {updated_count} промптов")


def reverse_fill(apps, schema_editor):
    """Откат не требуется, так как мы только добавляем данные"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0016_fill_professional_english_prompts'),
    ]

    operations = [
        migrations.RunPython(fill_english_prompts_part2, reverse_fill),
    ]
