# Generated by Django 5.2.6 on 2025-10-12 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0019_create_file_based_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="generation_type",
            field=models.CharField(
                choices=[("image", "Изображение"), ("video", "Видео")],
                db_index=True,
                default="image",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="result_video_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL видео"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_aspect_ratio",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Соотношение сторон"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_cached_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Видео кешировано до"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_camera_movement",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Движение камеры"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_duration",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Длительность видео (сек)"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_motion_strength",
            field=models.PositiveIntegerField(
                blank=True, default=45, null=True, verbose_name="Сила движения"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_resolution",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Разрешение"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_seed",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Seed"
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_source_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="video_sources/%Y/%m/",
                verbose_name="Исходное изображение",
            ),
        ),
        migrations.CreateModel(
            name="ShowcaseVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(max_length=500, verbose_name="URL видео"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="video_thumbnails/%Y/%m/", verbose_name="Превью"
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Название")),
                (
                    "prompt",
                    models.TextField(blank=True, default="", verbose_name="Промпт"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активно"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="generate.showcasecategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_showcase_videos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пример видео",
                "verbose_name_plural": "Примеры видео",
                "ordering": ("order", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "model_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="ID модели",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("t2v", "Text-to-Video"),
                            ("i2v", "Image-to-Video"),
                            ("anime", "Anime"),
                        ],
                        default="t2v",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "token_cost",
                    models.PositiveIntegerField(
                        default=18, verbose_name="Стоимость в токенах"
                    ),
                ),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Макс. длительность (сек)"
                    ),
                ),
                (
                    "max_resolution",
                    models.CharField(
                        default="1920x1080",
                        max_length=20,
                        verbose_name="Макс. разрешение",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Модель видео",
                "verbose_name_plural": "Модели видео",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "category", "order"],
                        name="generate_vi_is_acti_fbd9e1_idx",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="generationjob",
            name="video_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="generate.videomodel",
                verbose_name="Модель видео",
            ),
        ),
    ]
