# Generated by Django 5.2.6 on 2025-10-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0020_add_video_generation_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPromptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Слаг"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="video_prompt_categories/",
                        verbose_name="Изображение категории",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Категория промптов видео",
                "verbose_name_plural": "Категории промптов видео",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="generate_vi_is_acti_711032_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("prompt_text", models.TextField(verbose_name="Текст промпта")),
                (
                    "prompt_en",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Профессиональный английский промпт для генерации видео",
                        verbose_name="Английский промпт",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активен"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_prompts",
                        to="generate.videopromptcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промпт видео",
                "verbose_name_plural": "Промпты видео",
                "ordering": ("order", "title"),
                "indexes": [
                    models.Index(
                        fields=["category", "is_active", "order"],
                        name="generate_vi_categor_e10675_idx",
                    )
                ],
            },
        ),
    ]
