# Generated by Django 5.2.7 on 2025-10-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0022_add_mode_to_video_models"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videopromptcategory",
            name="generate_vi_is_acti_711032_idx",
        ),
        migrations.RenameIndex(
            model_name="showcasevideo",
            new_name="generate_sh_is_acti_452156_idx",
            old_fields=("is_active", "mode", "order"),
        ),
        migrations.RenameIndex(
            model_name="videopromptcategory",
            new_name="generate_vi_is_acti_08ba4f_idx",
            old_fields=("is_active", "mode", "order"),
        ),
        migrations.AlterField(
            model_name="promptcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="prompt_categories/",
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="showcasevideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to="video_thumbnails/%Y/%m/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="videopromptcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="video_prompt_categories/",
                verbose_name="Изображение категории",
            ),
        ),
    ]
