# Generated by Django 5.2.6 on 2025-10-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0023_add_wan25_preview"),
        (
            "generate",
            "0023_remove_videopromptcategory_generate_vi_is_acti_711032_idx_and_more",
        ),
    ]

    operations = []
