# Generated by Django 5.2.6 on 2025-10-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0024_merge_20251019_1704"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("slug", models.SlugField(max_length=140, verbose_name="Слаг")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="generate.promptcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория промптов",
                "verbose_name_plural": "Подкатегории промптов",
                "ordering": ("order", "name"),
            },
        ),
        migrations.AddField(
            model_name="categoryprompt",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prompts",
                to="generate.promptsubcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AddIndex(
            model_name="categoryprompt",
            index=models.Index(
                fields=["subcategory", "is_active", "order"],
                name="generate_ca_subcate_16ccff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promptsubcategory",
            index=models.Index(
                fields=["category", "is_active", "order"],
                name="generate_pr_categor_c92c67_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="promptsubcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"), name="uq_prompt_subcat_category_slug"
            ),
        ),
    ]
