# Generated by Django 5.2.7 on 2025-11-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0025_set_wan25_duration_10"),
        ("generate", "0027_generationjob_persisted"),
    ]

    operations = []
