# Generated by Django 5.2.7 on 2025-11-23 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0028_merge_20251109_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="references/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="Референсное изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружено"),
                ),
                (
                    "influence_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Сила влияния этого референса (0.0 - 1.0)",
                        verbose_name="Вес влияния",
                    ),
                ),
            ],
            options={
                "verbose_name": "Референсное изображение",
                "verbose_name_plural": "Референсные изображения",
                "ordering": ("order", "uploaded_at"),
            },
        ),
        migrations.RenameIndex(
            model_name="devicefingerprint",
            new_name="generate_de_fp_70c671_idx",
            old_name="device_fp_blocked_idx",
        ),
        migrations.RenameIndex(
            model_name="devicefingerprint",
            new_name="generate_de_gid_d2f244_idx",
            old_name="device_gid_blocked_idx",
        ),
        migrations.RenameIndex(
            model_name="devicefingerprint",
            new_name="generate_de_ip_hash_75eec1_idx",
            old_name="device_ip_blocked_idx",
        ),
        migrations.RenameIndex(
            model_name="devicefingerprint",
            new_name="generate_de_ua_hash_ae12be_idx",
            old_name="device_ua_blocked_idx",
        ),
        migrations.RenameIndex(
            model_name="devicefingerprint",
            new_name="generate_de_is_bloc_c1600b_idx",
            old_name="device_blocked_created_idx",
        ),
        migrations.RenameIndex(
            model_name="tokengrantattempt",
            new_name="generate_to_fp_b20c7c_idx",
            old_name="attempt_fp_created_idx",
        ),
        migrations.RenameIndex(
            model_name="tokengrantattempt",
            new_name="generate_to_gid_b7b50b_idx",
            old_name="attempt_gid_created_idx",
        ),
        migrations.RenameIndex(
            model_name="tokengrantattempt",
            new_name="generate_to_ip_hash_6d1e9b_idx",
            old_name="attempt_ip_created_idx",
        ),
        migrations.RenameIndex(
            model_name="tokengrantattempt",
            new_name="generate_to_was_blo_b92c88_idx",
            old_name="attempt_blocked_created_idx",
        ),
        migrations.AlterField(
            model_name="devicefingerprint",
            name="free_grant",
            field=models.OneToOneField(
                blank=True,
                help_text="Связанный грант",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_fingerprint",
                to="generate.freegrant",
            ),
        ),
        migrations.AlterField(
            model_name="tokengrantattempt",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grant_attempts",
                to="generate.devicefingerprint",
            ),
        ),
        migrations.AddField(
            model_name="referenceimage",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reference_images",
                to="generate.generationjob",
                verbose_name="Задача генерации",
            ),
        ),
        migrations.AddIndex(
            model_name="referenceimage",
            index=models.Index(
                fields=["job", "order"], name="generate_re_job_id_d06f11_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referenceimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("influence_weight__gte", 0.0), ("influence_weight__lte", 1.0)
                ),
                name="reference_image_influence_weight_range",
            ),
        ),
    ]
