# Generated by Django 5.2.6 on 2025-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0029_add_reference_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название модели"),
                ),
                (
                    "model_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID модели Runware",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Слаг"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("t2v", "Text-to-Video"),
                            ("i2v", "Image-to-Video"),
                            ("anime", "Anime"),
                            ("realistic", "Realistic"),
                            ("creative", "Creative"),
                        ],
                        db_index=True,
                        default="t2v",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "token_cost",
                    models.PositiveIntegerField(
                        default=18, verbose_name="Стоимость в токенах"
                    ),
                ),
                (
                    "supports_custom_resolution",
                    models.BooleanField(
                        default=False,
                        verbose_name="Поддерживает произвольное разрешение",
                    ),
                ),
                (
                    "resolution_512x512",
                    models.BooleanField(default=False, verbose_name="512x512"),
                ),
                (
                    "resolution_512x768",
                    models.BooleanField(default=False, verbose_name="512x768"),
                ),
                (
                    "resolution_512x1024",
                    models.BooleanField(default=False, verbose_name="512x1024"),
                ),
                (
                    "resolution_768x512",
                    models.BooleanField(default=False, verbose_name="768x512"),
                ),
                (
                    "resolution_768x768",
                    models.BooleanField(default=False, verbose_name="768x768"),
                ),
                (
                    "resolution_768x1024",
                    models.BooleanField(default=False, verbose_name="768x1024"),
                ),
                (
                    "resolution_1024x512",
                    models.BooleanField(default=False, verbose_name="1024x512"),
                ),
                (
                    "resolution_1024x768",
                    models.BooleanField(default=False, verbose_name="1024x768"),
                ),
                (
                    "resolution_1024x1024",
                    models.BooleanField(default=True, verbose_name="1024x1024"),
                ),
                (
                    "resolution_1280x720",
                    models.BooleanField(default=True, verbose_name="1280x720 (HD)"),
                ),
                (
                    "resolution_1920x1080",
                    models.BooleanField(
                        default=True, verbose_name="1920x1080 (Full HD)"
                    ),
                ),
                (
                    "resolution_2560x1440",
                    models.BooleanField(default=False, verbose_name="2560x1440 (2K)"),
                ),
                (
                    "resolution_3840x2160",
                    models.BooleanField(default=False, verbose_name="3840x2160 (4K)"),
                ),
                (
                    "min_width",
                    models.PositiveIntegerField(
                        default=512, verbose_name="Минимальная ширина"
                    ),
                ),
                (
                    "max_width",
                    models.PositiveIntegerField(
                        default=1920, verbose_name="Максимальная ширина"
                    ),
                ),
                (
                    "min_height",
                    models.PositiveIntegerField(
                        default=512, verbose_name="Минимальная высота"
                    ),
                ),
                (
                    "max_height",
                    models.PositiveIntegerField(
                        default=1080, verbose_name="Максимальная высота"
                    ),
                ),
                (
                    "aspect_ratio_1_1",
                    models.BooleanField(default=True, verbose_name="1:1 (Квадрат)"),
                ),
                (
                    "aspect_ratio_16_9",
                    models.BooleanField(
                        default=True, verbose_name="16:9 (Широкоэкранный)"
                    ),
                ),
                (
                    "aspect_ratio_9_16",
                    models.BooleanField(
                        default=True, verbose_name="9:16 (Вертикальный)"
                    ),
                ),
                (
                    "aspect_ratio_4_3",
                    models.BooleanField(
                        default=False, verbose_name="4:3 (Стандартный)"
                    ),
                ),
                (
                    "aspect_ratio_3_4",
                    models.BooleanField(
                        default=False, verbose_name="3:4 (Вертикальный стандартный)"
                    ),
                ),
                (
                    "aspect_ratio_21_9",
                    models.BooleanField(
                        default=False, verbose_name="21:9 (Ультраширокий)"
                    ),
                ),
                (
                    "supports_custom_duration",
                    models.BooleanField(
                        default=False,
                        verbose_name="Поддерживает произвольную длительность",
                    ),
                ),
                (
                    "duration_2",
                    models.BooleanField(default=False, verbose_name="2 секунды"),
                ),
                (
                    "duration_3",
                    models.BooleanField(default=False, verbose_name="3 секунды"),
                ),
                (
                    "duration_4",
                    models.BooleanField(default=True, verbose_name="4 секунды"),
                ),
                (
                    "duration_5",
                    models.BooleanField(default=True, verbose_name="5 секунды"),
                ),
                (
                    "duration_6",
                    models.BooleanField(default=False, verbose_name="6 секунд"),
                ),
                (
                    "duration_8",
                    models.BooleanField(default=True, verbose_name="8 секунд"),
                ),
                (
                    "duration_10",
                    models.BooleanField(default=True, verbose_name="10 секунд"),
                ),
                (
                    "duration_15",
                    models.BooleanField(default=False, verbose_name="15 секунд"),
                ),
                (
                    "duration_20",
                    models.BooleanField(default=False, verbose_name="20 секунд"),
                ),
                (
                    "duration_30",
                    models.BooleanField(default=False, verbose_name="30 секунд"),
                ),
                (
                    "min_duration",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Минимальная длительность (сек)"
                    ),
                ),
                (
                    "max_duration",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Максимальная длительность (сек)"
                    ),
                ),
                (
                    "supports_camera_movement",
                    models.BooleanField(
                        default=True, verbose_name="Поддерживает движение камеры"
                    ),
                ),
                (
                    "camera_static",
                    models.BooleanField(default=True, verbose_name="Статичная камера"),
                ),
                (
                    "camera_pan_left",
                    models.BooleanField(default=True, verbose_name="Панорама влево"),
                ),
                (
                    "camera_pan_right",
                    models.BooleanField(default=True, verbose_name="Панорама вправо"),
                ),
                (
                    "camera_tilt_up",
                    models.BooleanField(default=True, verbose_name="Наклон вверх"),
                ),
                (
                    "camera_tilt_down",
                    models.BooleanField(default=True, verbose_name="Наклон вниз"),
                ),
                (
                    "camera_zoom_in",
                    models.BooleanField(default=True, verbose_name="Приближение"),
                ),
                (
                    "camera_zoom_out",
                    models.BooleanField(default=True, verbose_name="Отдаление"),
                ),
                (
                    "camera_dolly_in",
                    models.BooleanField(default=False, verbose_name="Движение вперёд"),
                ),
                (
                    "camera_dolly_out",
                    models.BooleanField(default=False, verbose_name="Движение назад"),
                ),
                (
                    "camera_orbit_left",
                    models.BooleanField(default=False, verbose_name="Орбита влево"),
                ),
                (
                    "camera_orbit_right",
                    models.BooleanField(default=False, verbose_name="Орбита вправо"),
                ),
                (
                    "camera_crane_up",
                    models.BooleanField(default=False, verbose_name="Кран вверх"),
                ),
                (
                    "camera_crane_down",
                    models.BooleanField(default=False, verbose_name="Кран вниз"),
                ),
                (
                    "supports_image_to_video",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает Image-to-Video"
                    ),
                ),
                (
                    "supports_motion_strength",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает силу движения"
                    ),
                ),
                (
                    "min_motion_strength",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Минимальная сила движения"
                    ),
                ),
                (
                    "max_motion_strength",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Максимальная сила движения"
                    ),
                ),
                (
                    "default_motion_strength",
                    models.PositiveIntegerField(
                        default=45, verbose_name="Сила движения по умолчанию"
                    ),
                ),
                (
                    "supports_seed",
                    models.BooleanField(default=True, verbose_name="Поддерживает seed"),
                ),
                (
                    "supports_fps",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает настройку FPS"
                    ),
                ),
                (
                    "min_fps",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Минимальный FPS"
                    ),
                ),
                (
                    "max_fps",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Максимальный FPS"
                    ),
                ),
                (
                    "default_fps",
                    models.PositiveIntegerField(
                        default=30, verbose_name="FPS по умолчанию"
                    ),
                ),
                (
                    "supports_quality",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает настройку качества"
                    ),
                ),
                (
                    "quality_low",
                    models.BooleanField(default=False, verbose_name="Низкое качество"),
                ),
                (
                    "quality_medium",
                    models.BooleanField(default=True, verbose_name="Среднее качество"),
                ),
                (
                    "quality_high",
                    models.BooleanField(default=True, verbose_name="Высокое качество"),
                ),
                (
                    "quality_ultra",
                    models.BooleanField(default=False, verbose_name="Ультра качество"),
                ),
                (
                    "supports_style_presets",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает стилевые пресеты"
                    ),
                ),
                (
                    "style_realistic",
                    models.BooleanField(default=False, verbose_name="Реалистичный"),
                ),
                (
                    "style_anime",
                    models.BooleanField(default=False, verbose_name="Аниме"),
                ),
                (
                    "style_cartoon",
                    models.BooleanField(default=False, verbose_name="Мультяшный"),
                ),
                (
                    "style_cinematic",
                    models.BooleanField(
                        default=False, verbose_name="Кинематографичный"
                    ),
                ),
                (
                    "style_artistic",
                    models.BooleanField(default=False, verbose_name="Художественный"),
                ),
                (
                    "supports_negative_prompt",
                    models.BooleanField(
                        default=True, verbose_name="Поддерживает негативный промпт"
                    ),
                ),
                (
                    "supports_guidance_scale",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает guidance scale"
                    ),
                ),
                (
                    "min_guidance_scale",
                    models.FloatField(
                        default=1.0, verbose_name="Минимальный guidance scale"
                    ),
                ),
                (
                    "max_guidance_scale",
                    models.FloatField(
                        default=20.0, verbose_name="Максимальный guidance scale"
                    ),
                ),
                (
                    "default_guidance_scale",
                    models.FloatField(
                        default=7.5, verbose_name="Guidance scale по умолчанию"
                    ),
                ),
                (
                    "supports_inference_steps",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает количество шагов"
                    ),
                ),
                (
                    "min_inference_steps",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Минимум шагов"
                    ),
                ),
                (
                    "max_inference_steps",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Максимум шагов"
                    ),
                ),
                (
                    "default_inference_steps",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Шагов по умолчанию"
                    ),
                ),
                (
                    "supports_mp4",
                    models.BooleanField(default=True, verbose_name="Поддерживает MP4"),
                ),
                (
                    "supports_webm",
                    models.BooleanField(
                        default=False, verbose_name="Поддерживает WebM"
                    ),
                ),
                (
                    "supports_gif",
                    models.BooleanField(default=False, verbose_name="Поддерживает GIF"),
                ),
                (
                    "supports_watermark_removal",
                    models.BooleanField(
                        default=False,
                        verbose_name="Поддерживает удаление водяного знака",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "is_beta",
                    models.BooleanField(default=False, verbose_name="Бета-версия"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Премиум модель"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="Runware", max_length=50, verbose_name="Провайдер"
                    ),
                ),
                (
                    "provider_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Версия провайдера",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Заметки администратора"
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация видео модели",
                "verbose_name_plural": "Конфигурации видео моделей",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "category", "order"],
                        name="generate_vi_is_acti_7aded1_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_premium", "order"],
                        name="generate_vi_is_acti_799a13_idx",
                    ),
                ],
            },
        ),
    ]
