# Generated by Django 5.2.6 on 2025-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0030_add_video_model_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Превью или иконка модели для отображения в интерфейсе",
                null=True,
                upload_to="video_models/%Y/%m/",
                verbose_name="Изображение модели",
            ),
        ),
    ]
