# Generated by Django 5.2.6 on 2025-11-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0031_add_image_to_video_model_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="category",
            field=models.CharField(
                choices=[
                    ("t2v", "Text-to-Video"),
                    ("i2v", "Image-to-Video"),
                    ("both", "T2V и I2V"),
                    ("anime", "Anime"),
                    ("realistic", "Realistic"),
                    ("creative", "Creative"),
                ],
                db_index=True,
                default="t2v",
                help_text="Выберите где модель будет доступна: только T2V, только I2V или в обеих категориях",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
