# Generated by Django 5.2.6 on 2025-11-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0032_add_category_both_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="default_fps",
            field=models.PositiveIntegerField(
                blank=True, default=30, null=True, verbose_name="FPS по умолчанию"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="default_guidance_scale",
            field=models.FloatField(
                blank=True,
                default=7.5,
                null=True,
                verbose_name="Guidance scale по умолчанию",
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="default_inference_steps",
            field=models.PositiveIntegerField(
                blank=True, default=50, null=True, verbose_name="Шагов по умолчанию"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="default_motion_strength",
            field=models.PositiveIntegerField(
                blank=True,
                default=45,
                null=True,
                verbose_name="Сила движения по умолчанию",
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="max_fps",
            field=models.PositiveIntegerField(
                blank=True, default=60, null=True, verbose_name="Максимальный FPS"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="max_guidance_scale",
            field=models.FloatField(
                blank=True,
                default=20.0,
                null=True,
                verbose_name="Максимальный guidance scale",
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="max_inference_steps",
            field=models.PositiveIntegerField(
                blank=True, default=100, null=True, verbose_name="Максимум шагов"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="max_motion_strength",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                null=True,
                verbose_name="Максимальная сила движения",
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="min_fps",
            field=models.PositiveIntegerField(
                blank=True, default=24, null=True, verbose_name="Минимальный FPS"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="min_guidance_scale",
            field=models.FloatField(
                blank=True,
                default=1.0,
                null=True,
                verbose_name="Минимальный guidance scale",
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="min_inference_steps",
            field=models.PositiveIntegerField(
                blank=True, default=10, null=True, verbose_name="Минимум шагов"
            ),
        ),
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="min_motion_strength",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Минимальная сила движения",
            ),
        ),
    ]
