# Generated by Django 5.2.6 on 2025-11-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0033_alter_videomodelconfiguration_default_fps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="optional_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON конфигурация доступных полей для пользователя",
                verbose_name="Опциональные поля",
            ),
        ),
    ]
