# Generated by Django 5.2.6 on 2025-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0034_videomodelconfiguration_optional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="category",
            field=models.CharField(
                choices=[
                    ("t2v", "Text-to-Video (Генерация видео)"),
                    ("i2v", "Image-to-Video (Оживить фото)"),
                ],
                db_index=True,
                default="t2v",
                help_text="T2V = модель появится в 'Генерация видео', I2V = модель появится в 'Оживить фото'",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
