# Generated by Django 5.2.6 on 2025-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0035_alter_videomodelconfiguration_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videomodelconfiguration",
            name="model_id",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="ID модели Runware"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="videomodelconfiguration",
            unique_together={("model_id", "category")},
        ),
    ]
