# Generated by Django 5.2.6 on 2025-11-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0036_alter_videomodelconfiguration_model_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="supports_reference_images",
            field=models.BooleanField(
                default=False, verbose_name="Поддерживает референсные изображения"
            ),
        ),
    ]
