# Generated by Django 5.2.6 on 2025-11-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0037_add_reference_images_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Отображаемое название модели",
                        max_length=100,
                        verbose_name="Название модели",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID модели в формате provider:id@version (например: runware:101@1)",
                        max_length=100,
                        unique=True,
                        verbose_name="ID модели Runware",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Описание модели для пользователей",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Превью модели",
                        null=True,
                        upload_to="image_models/",
                        verbose_name="Изображение модели",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="Runware",
                        help_text="Название провайдера (Runware, ByteDance, BFL и т.д.)",
                        max_length=50,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "token_cost",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Стоимость одной генерации",
                        verbose_name="Стоимость в токенах",
                    ),
                ),
                (
                    "resolution_512x512",
                    models.BooleanField(default=False, verbose_name="512x512"),
                ),
                (
                    "resolution_512x768",
                    models.BooleanField(default=False, verbose_name="512x768"),
                ),
                (
                    "resolution_512x1024",
                    models.BooleanField(default=False, verbose_name="512x1024"),
                ),
                (
                    "resolution_768x512",
                    models.BooleanField(default=False, verbose_name="768x512"),
                ),
                (
                    "resolution_768x768",
                    models.BooleanField(default=False, verbose_name="768x768"),
                ),
                (
                    "resolution_768x1024",
                    models.BooleanField(default=False, verbose_name="768x1024"),
                ),
                (
                    "resolution_1024x512",
                    models.BooleanField(default=False, verbose_name="1024x512"),
                ),
                (
                    "resolution_1024x768",
                    models.BooleanField(default=False, verbose_name="1024x768"),
                ),
                (
                    "resolution_1024x1024",
                    models.BooleanField(default=True, verbose_name="1024x1024"),
                ),
                (
                    "resolution_1280x720",
                    models.BooleanField(default=False, verbose_name="1280x720 (HD)"),
                ),
                (
                    "resolution_1920x1080",
                    models.BooleanField(
                        default=False, verbose_name="1920x1080 (Full HD)"
                    ),
                ),
                (
                    "resolution_2560x1440",
                    models.BooleanField(default=False, verbose_name="2560x1440 (2K)"),
                ),
                (
                    "resolution_3840x2160",
                    models.BooleanField(default=False, verbose_name="3840x2160 (4K)"),
                ),
                (
                    "supports_custom_resolution",
                    models.BooleanField(
                        default=False,
                        verbose_name="Поддерживает произвольное разрешение",
                    ),
                ),
                (
                    "min_width",
                    models.PositiveIntegerField(
                        default=512,
                        help_text="Минимальная ширина изображения в пикселях",
                        verbose_name="Минимальная ширина",
                    ),
                ),
                (
                    "max_width",
                    models.PositiveIntegerField(
                        default=2048,
                        help_text="Максимальная ширина изображения в пикселях",
                        verbose_name="Максимальная ширина",
                    ),
                ),
                (
                    "min_height",
                    models.PositiveIntegerField(
                        default=512,
                        help_text="Минимальная высота изображения в пикселях",
                        verbose_name="Минимальная высота",
                    ),
                ),
                (
                    "max_height",
                    models.PositiveIntegerField(
                        default=2048,
                        help_text="Максимальная высота изображения в пикселях",
                        verbose_name="Максимальная высота",
                    ),
                ),
                (
                    "supports_steps",
                    models.BooleanField(
                        default=True,
                        help_text="Inference steps",
                        verbose_name="Поддерживает настройку шагов",
                    ),
                ),
                (
                    "min_steps",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Минимум шагов"
                    ),
                ),
                (
                    "max_steps",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Максимум шагов"
                    ),
                ),
                (
                    "default_steps",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Шагов по умолчанию"
                    ),
                ),
                (
                    "supports_cfg_scale",
                    models.BooleanField(
                        default=True,
                        help_text="Guidance scale",
                        verbose_name="Поддерживает CFG Scale",
                    ),
                ),
                (
                    "min_cfg_scale",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=4,
                        verbose_name="Минимум CFG",
                    ),
                ),
                (
                    "max_cfg_scale",
                    models.DecimalField(
                        decimal_places=1,
                        default=20.0,
                        max_digits=4,
                        verbose_name="Максимум CFG",
                    ),
                ),
                (
                    "default_cfg_scale",
                    models.DecimalField(
                        decimal_places=1,
                        default=7.0,
                        max_digits=4,
                        verbose_name="CFG по умолчанию",
                    ),
                ),
                (
                    "supports_scheduler",
                    models.BooleanField(
                        default=True, verbose_name="Поддерживает выбор scheduler"
                    ),
                ),
                (
                    "supports_seed",
                    models.BooleanField(default=True, verbose_name="Поддерживает seed"),
                ),
                (
                    "supports_negative_prompt",
                    models.BooleanField(
                        default=True, verbose_name="Поддерживает негативный промпт"
                    ),
                ),
                (
                    "supports_reference_images",
                    models.BooleanField(
                        default=False,
                        help_text="Модель поддерживает референсные изображения (FLUX.1 Kontext, Ace++)",
                        verbose_name="Поддерживает референсные изображения",
                    ),
                ),
                (
                    "max_reference_images",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Максимальное количество референсных изображений (1-2)",
                        verbose_name="Максимум референсов",
                    ),
                ),
                (
                    "is_special_model",
                    models.BooleanField(
                        default=False,
                        help_text="Модель требует особой обработки (Flux, Seedream и т.д.)",
                        verbose_name="Специальная модель",
                    ),
                ),
                (
                    "uses_jpeg_format",
                    models.BooleanField(
                        default=False,
                        help_text="Для специальных моделей (Flux, Seedream)",
                        verbose_name="Использует JPEG формат",
                    ),
                ),
                (
                    "include_cost_in_request",
                    models.BooleanField(
                        default=False,
                        help_text="Добавлять includeCost в запрос (для специальных моделей)",
                        verbose_name="Включать стоимость в запрос",
                    ),
                ),
                (
                    "supports_multiple_results",
                    models.BooleanField(
                        default=True, verbose_name="Поддерживает несколько результатов"
                    ),
                ),
                (
                    "max_number_results",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Максимальное количество изображений за раз",
                        verbose_name="Максимум результатов",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Активна"
                    ),
                ),
                (
                    "is_beta",
                    models.BooleanField(default=False, verbose_name="Бета-версия"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Премиум модель"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Порядок отображения в списке (меньше = выше)",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Внутренние заметки (не видны пользователям)",
                        verbose_name="Заметки администратора",
                    ),
                ),
                (
                    "optional_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Какие поля показывать пользователю при генерации",
                        verbose_name="Доступные параметры",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Конфигурация модели изображений",
                "verbose_name_plural": "Конфигурации моделей изображений",
                "ordering": ("order", "name"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="generate_im_is_acti_3afde2_idx",
                    ),
                    models.Index(
                        fields=["provider", "is_active"],
                        name="generate_im_provide_49e5df_idx",
                    ),
                ],
            },
        ),
    ]
