# Generated by Django 5.2.6 on 2025-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0038_add_image_model_configuration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="default_cfg_scale",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=7.0,
                max_digits=4,
                verbose_name="CFG по умолчанию",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="default_steps",
            field=models.PositiveIntegerField(
                blank=True, default=20, verbose_name="Шагов по умолчанию"
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="max_cfg_scale",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=20.0,
                max_digits=4,
                verbose_name="Максимум CFG",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="max_number_results",
            field=models.PositiveIntegerField(
                blank=True,
                default=4,
                help_text="Максимальное количество изображений за раз",
                verbose_name="Максимум результатов",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="max_reference_images",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Максимальное количество референсных изображений (1-2)",
                verbose_name="Максимум референсов",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="max_steps",
            field=models.PositiveIntegerField(
                blank=True, default=50, verbose_name="Максимум шагов"
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="min_cfg_scale",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=1.0,
                max_digits=4,
                verbose_name="Минимум CFG",
            ),
        ),
        migrations.AlterField(
            model_name="imagemodelconfiguration",
            name="min_steps",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Минимум шагов"
            ),
        ),
    ]
