# Generated by Django 5.2.7 on 2025-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0039_alter_imagemodelconfiguration_default_cfg_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="default_videos",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Количество по умолчанию"
            ),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="max_videos",
            field=models.PositiveIntegerField(
                blank=True, default=4, null=True, verbose_name="Максимум видео"
            ),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="min_videos",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Минимум видео"
            ),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="supports_multiple_videos",
            field=models.BooleanField(
                default=False,
                help_text="Позволяет генерировать несколько видео за раз",
                verbose_name="Поддерживает множественную генерацию",
            ),
        ),
    ]
