# Generated by Django 5.2.7 on 2025-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0040_add_multiple_videos_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_120",
            field=models.BooleanField(default=False, verbose_name="120 FPS"),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_15",
            field=models.BooleanField(default=False, verbose_name="15 FPS"),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_24",
            field=models.BooleanField(default=True, verbose_name="24 FPS"),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_30",
            field=models.BooleanField(default=True, verbose_name="30 FPS"),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_60",
            field=models.BooleanField(default=False, verbose_name="60 FPS"),
        ),
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="fps_90",
            field=models.BooleanField(default=False, verbose_name="90 FPS"),
        ),
    ]
