# Generated by Django 5.2.7 on 2025-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generate", "0041_add_fps_checkboxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="videomodelconfiguration",
            name="duration_12",
            field=models.BooleanField(default=False, verbose_name="12 секунд"),
        ),
    ]
