# Generated by Django 5.2.6 on 2025-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0042_add_duration_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='supported_references',
            field=models.JSONField(blank=True, default=list, help_text='Типы входных данных, которые поддерживает модель (frameImages, referenceImages, audioInputs, controlNet)', verbose_name='Поддерживаемые референсы'),
        ),
    ]
