# Generated by Django 5.2.6 on 2025-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0043_videomodel_supported_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='supported_references',
            field=models.JSONField(blank=True, default=list, help_text='Типы входных данных: frameImages, referenceImages, audioInputs, controlNet', verbose_name='Поддерживаемые референсы'),
        ),
    ]
