# Generated by Django 5.2.6 on 2025-12-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0044_add_video_model_config_supported_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefingerprint',
            name='server_fp',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Серверный отпечаток (fallback)', max_length=64),
        ),
        migrations.AlterField(
            model_name='devicefingerprint',
            name='fp',
            field=models.CharField(db_index=True, help_text='Клиентский отпечаток браузера (canvas+WebGL)', max_length=64),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['server_fp', 'is_blocked'], name='generate_de_server__515fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['gid', 'ua_hash'], name='generate_de_gid_00b669_idx'),
        ),
    ]
