# Generated by Django 5.2.6 on 2025-12-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0045_add_server_fp_to_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_10_16',
            field=models.BooleanField(default=False, verbose_name='10:16'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_15_9',
            field=models.BooleanField(default=False, verbose_name='15:9 — редкий переходный формат'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_16_10',
            field=models.BooleanField(default=False, verbose_name='16:10 — рабочие мониторы, ноутбуки'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_16_9',
            field=models.BooleanField(default=True, verbose_name='16:9 — основной стандарт (мониторы, ТВ, YouTube)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_17_9',
            field=models.BooleanField(default=False, verbose_name='17:9 — цифровое кино (DCI)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_18_9',
            field=models.BooleanField(default=False, verbose_name='18:9 (≈2:1)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_19_9',
            field=models.BooleanField(default=False, verbose_name='19:9'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_1_1',
            field=models.BooleanField(default=True, verbose_name='1:1 — квадрат (соцсети, иконки)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_1_85_1',
            field=models.BooleanField(default=False, verbose_name='1.85:1 — кинотеатры (Flat)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_20_9',
            field=models.BooleanField(default=False, verbose_name='20:9'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_21_9',
            field=models.BooleanField(default=False, verbose_name='21:9 — ультраширокие мониторы'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_24_10',
            field=models.BooleanField(default=False, verbose_name='24:10'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_00_1',
            field=models.BooleanField(default=False, verbose_name='2.00:1 — Netflix, современные сериалы'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_20_1',
            field=models.BooleanField(default=False, verbose_name='2.20:1 — 70mm плёнка'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_3',
            field=models.BooleanField(default=False, verbose_name='2:3 — фото'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_35_1',
            field=models.BooleanField(default=False, verbose_name='2.35:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_39_1',
            field=models.BooleanField(default=False, verbose_name='2.39:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_2_40_1',
            field=models.BooleanField(default=False, verbose_name='2.40:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_32_9',
            field=models.BooleanField(default=False, verbose_name='32:9 — суперультраширокие'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_3_2',
            field=models.BooleanField(default=False, verbose_name='3:2 — фотоаппараты, плёнка'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_3_4',
            field=models.BooleanField(default=False, verbose_name='3:4 — вертикальный стандарт'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_4_3',
            field=models.BooleanField(default=False, verbose_name='4:3 — стандарт (CRT, старые камеры)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_4_5',
            field=models.BooleanField(default=False, verbose_name='4:5 — Instagram'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_5_4',
            field=models.BooleanField(default=False, verbose_name='5:4 — старые LCD (1280×1024)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_5_8',
            field=models.BooleanField(default=False, verbose_name='5:8'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_7_5',
            field=models.BooleanField(default=False, verbose_name='7:5'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_8_10',
            field=models.BooleanField(default=False, verbose_name='8:10 — портретная печать'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_9_16',
            field=models.BooleanField(default=True, verbose_name='9:16 — основной вертикальный (Stories, Reels)'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_9_19_5',
            field=models.BooleanField(default=False, verbose_name='9:19.5'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_9_20',
            field=models.BooleanField(default=False, verbose_name='9:20'),
        ),
        migrations.AddField(
            model_name='imagemodelconfiguration',
            name='aspect_ratio_9_21',
            field=models.BooleanField(default=False, verbose_name='9:21'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_10_16',
            field=models.BooleanField(default=False, verbose_name='10:16'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_15_9',
            field=models.BooleanField(default=False, verbose_name='15:9 — редкий переходный формат'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_16_10',
            field=models.BooleanField(default=False, verbose_name='16:10 — рабочие мониторы, ноутбуки'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_17_9',
            field=models.BooleanField(default=False, verbose_name='17:9 — цифровое кино (DCI)'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_18_9',
            field=models.BooleanField(default=False, verbose_name='18:9 (≈2:1)'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_19_9',
            field=models.BooleanField(default=False, verbose_name='19:9'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_1_85_1',
            field=models.BooleanField(default=False, verbose_name='1.85:1 — кинотеатры (Flat)'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_20_9',
            field=models.BooleanField(default=False, verbose_name='20:9'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_24_10',
            field=models.BooleanField(default=False, verbose_name='24:10'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_00_1',
            field=models.BooleanField(default=False, verbose_name='2.00:1 — Netflix, современные сериалы'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_20_1',
            field=models.BooleanField(default=False, verbose_name='2.20:1 — 70mm плёнка'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_3',
            field=models.BooleanField(default=False, verbose_name='2:3 — фото'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_35_1',
            field=models.BooleanField(default=False, verbose_name='2.35:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_39_1',
            field=models.BooleanField(default=False, verbose_name='2.39:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_2_40_1',
            field=models.BooleanField(default=False, verbose_name='2.40:1 — CinemaScope'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_32_9',
            field=models.BooleanField(default=False, verbose_name='32:9 — суперультраширокие'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_3_2',
            field=models.BooleanField(default=False, verbose_name='3:2 — фотоаппараты, плёнка'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_4_5',
            field=models.BooleanField(default=False, verbose_name='4:5 — Instagram'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_5_4',
            field=models.BooleanField(default=False, verbose_name='5:4 — старые LCD (1280×1024)'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_5_8',
            field=models.BooleanField(default=False, verbose_name='5:8'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_7_5',
            field=models.BooleanField(default=False, verbose_name='7:5'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_8_10',
            field=models.BooleanField(default=False, verbose_name='8:10 — портретная печать'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_9_19_5',
            field=models.BooleanField(default=False, verbose_name='9:19.5'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_9_20',
            field=models.BooleanField(default=False, verbose_name='9:20'),
        ),
        migrations.AddField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_9_21',
            field=models.BooleanField(default=False, verbose_name='9:21'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_16_9',
            field=models.BooleanField(default=True, verbose_name='16:9 — основной стандарт (мониторы, ТВ, YouTube)'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_1_1',
            field=models.BooleanField(default=True, verbose_name='1:1 — квадрат (соцсети, иконки)'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_21_9',
            field=models.BooleanField(default=False, verbose_name='21:9 — ультраширокие мониторы'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_3_4',
            field=models.BooleanField(default=False, verbose_name='3:4 — вертикальный стандарт'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_4_3',
            field=models.BooleanField(default=False, verbose_name='4:3 — стандарт (CRT, старые камеры)'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='aspect_ratio_9_16',
            field=models.BooleanField(default=True, verbose_name='9:16 — основной вертикальный (Stories, Reels)'),
        ),
    ]
