# Generated by Django 5.2.6 on 2025-12-22 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0046_imagemodelconfiguration_aspect_ratio_10_16_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatioPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Описательное название (например: 'Instagram Stories')", max_length=100, verbose_name='Название')),
                ('aspect_ratio', models.CharField(max_length=20, unique=True, verbose_name='Соотношение')),
                ('category', models.CharField(blank=True, help_text='Группировка (соцсети, кино, фото и т.д.)', max_length=50, verbose_name='Категория')),
                ('icon', models.CharField(blank=True, help_text='Emoji иконка для отображения', max_length=10, verbose_name='Иконка')),
                ('description', models.TextField(blank=True, help_text='Где используется это соотношение', verbose_name='Описание')),
                ('recommended_sd', models.CharField(blank=True, help_text='Например: 640x480', max_length=20, verbose_name='SD рекомендация')),
                ('recommended_hd', models.CharField(blank=True, help_text='Например: 1280x720', max_length=20, verbose_name='HD рекомендация')),
                ('recommended_full_hd', models.CharField(blank=True, help_text='Например: 1920x1080', max_length=20, verbose_name='Full HD рекомендация')),
                ('recommended_2k', models.CharField(blank=True, help_text='Например: 2560x1440', max_length=20, verbose_name='2K рекомендация')),
                ('recommended_4k', models.CharField(blank=True, help_text='Например: 3840x2160', max_length=20, verbose_name='4K рекомендация')),
                ('recommended_8k', models.CharField(blank=True, help_text='Например: 7680x4320', max_length=20, verbose_name='8K рекомендация')),
                ('is_common', models.BooleanField(default=False, help_text='Часто используемое соотношение', verbose_name='Популярное')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Предустановка соотношения сторон',
                'verbose_name_plural': 'Предустановки соотношений сторон',
                'ordering': ['-is_common', 'order', 'aspect_ratio'],
            },
        ),
        migrations.CreateModel(
            name='AspectRatioQualityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео')], db_index=True, max_length=20, verbose_name='Тип модели')),
                ('model_id', models.PositiveIntegerField(db_index=True, help_text='ID ImageModelConfiguration или VideoModelConfiguration', verbose_name='ID модели')),
                ('aspect_ratio', models.CharField(db_index=True, help_text='Например: 1:1, 16:9, 9:16, 4:5, 21:9', max_length=20, verbose_name='Соотношение сторон')),
                ('quality', models.CharField(choices=[('sd', 'SD (480p)'), ('hd', 'HD (720p)'), ('full_hd', 'Full HD (1080p)'), ('2k', '2K (1440p)'), ('4k', '4K (2160p)'), ('8k', '8K (4320p)')], db_index=True, max_length=20, verbose_name='Качество')),
                ('width', models.PositiveIntegerField(help_text='Точная ширина в пикселях (проверено на Runware)', validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(8192)], verbose_name='Ширина (px)')),
                ('height', models.PositiveIntegerField(help_text='Точная высота в пикселях (проверено на Runware)', validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(8192)], verbose_name='Высота (px)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать эту комбинацию по умолчанию для модели', verbose_name='По умолчанию')),
                ('order', models.PositiveIntegerField(default=0, help_text='Меньше = выше в списке', verbose_name='Порядок отображения')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки (результаты тестов на Runware, особенности и т.д.)', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Конфигурация соотношения и качества',
                'verbose_name_plural': 'Конфигурации соотношений и качества',
                'ordering': ['model_type', 'model_id', 'order', 'aspect_ratio', 'quality'],
                'indexes': [models.Index(fields=['model_type', 'model_id', 'is_active'], name='generate_as_model_t_13f6f0_idx'), models.Index(fields=['aspect_ratio', 'quality'], name='generate_as_aspect__b2ebfa_idx')],
                'unique_together': {('model_type', 'model_id', 'aspect_ratio', 'quality')},
            },
        ),
    ]
