# Generated by Django 5.2.6 on 2025-12-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0047_add_aspect_ratio_quality_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodelconfiguration',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, default=2048, help_text='Максимальная высота изображения в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Максимальная высота'),
        ),
        migrations.AlterField(
            model_name='imagemodelconfiguration',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, default=2048, help_text='Максимальная ширина изображения в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Максимальная ширина'),
        ),
        migrations.AlterField(
            model_name='imagemodelconfiguration',
            name='min_height',
            field=models.PositiveIntegerField(blank=True, default=512, help_text='Минимальная высота изображения в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Минимальная высота'),
        ),
        migrations.AlterField(
            model_name='imagemodelconfiguration',
            name='min_width',
            field=models.PositiveIntegerField(blank=True, default=512, help_text='Минимальная ширина изображения в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Минимальная ширина'),
        ),
    ]
