# Generated by Django 5.2.6 on 2025-12-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0048_make_dimension_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, default=1080, help_text='Максимальная высота видео в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Максимальная высота'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, default=1920, help_text='Максимальная ширина видео в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Максимальная ширина'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='min_height',
            field=models.PositiveIntegerField(blank=True, default=512, help_text='Минимальная высота видео в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Минимальная высота'),
        ),
        migrations.AlterField(
            model_name='videomodelconfiguration',
            name='min_width',
            field=models.PositiveIntegerField(blank=True, default=512, help_text='Минимальная ширина видео в пикселях (устаревшее, используйте конфигурацию соотношений сторон)', null=True, verbose_name='Минимальная ширина'),
        ),
    ]
